<?php

/**
 * - load
 * - install
 * - uninstall
 * Appel au Pelican_Cache avec id du plugin
 *
 */
class Module_FormBuilder extends Pelican_Plugin
{

    /**
     * DÃ©fintion de constantes ou traitements d'initialisation du plugin au chargement
     */
    public function load ()
    {}

    /**
     * Ã  lancer lors de l'installation du plugin :
     * - insertion de donnÃ©es
     * - crÃ©ation d'une table
     * - crÃ©ation de rÃ©pertoires etc...
     */
    public function install ()
    {
        $oConnection = Pelican_Db::getInstance();
        
        $sql[] = "DROP TABLE IF EXISTS #pref#_formbuilder";
        
        $sql[] = "CREATE TABLE IF NOT EXISTS #pref#_formbuilder (
  FORMBUILDER_ID int(11) NOT NULL auto_increment,
  SITE_ID int(11) NOT NULL,
  FORMBUILDER_LABEL varchar(255) collate utf8_swedish_ci NOT NULL default '-Sans nom-',
  LANGUE_ID int(11) NOT NULL,
  FORMBUILDER_STRUCTURE longtext collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_TRANSLATION longtext collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_MODE enum('mail','database') collate utf8_swedish_ci NOT NULL default 'mail',
  FORMBUILDER_CSS text collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_SMTP_HOST varchar(255) collate utf8_swedish_ci default NULL,
  FORMBUILDER_SMTP_USER varchar(255) collate utf8_swedish_ci default NULL,
  FORMBUILDER_SMTP_PWD varchar(255) collate utf8_swedish_ci default NULL,
  FORMBUILDER_FIELDS varchar(500) collate utf8_swedish_ci default NULL,
  PRIMARY KEY  (FORMBUILDER_ID),
  KEY LANGUE_ID (LANGUE_ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci";
        
        $sql[] = "DROP TABLE IF EXISTS #pref#_formbuilder_mail";
        
        $sql[] = "CREATE TABLE IF NOT EXISTS #pref#_formbuilder_mail (
  FORMBUILDER_ID int(11) NOT NULL auto_increment,
  FORMBUILDER_MAIL_TYPE varchar(100) collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_MAIL_SUBJECT varchar(255) collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_MAIL_CC text collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_MAIL_CCI text collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_MAIL_EXP varchar(320) collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_MAIL_DEST varchar(320) collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_MAIL_BODY_TYPE varchar(4) collate utf8_swedish_ci NOT NULL default 'text',
  FORMBUILDER_MAIL_BODY_HTML text collate utf8_swedish_ci,
  FORMBUILDER_MAIL_BODY_TEXT text collate utf8_swedish_ci,
  PRIMARY KEY  (FORMBUILDER_ID,FORMBUILDER_MAIL_TYPE)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci";
        
        $sql[] = "DROP TABLE IF EXISTS #pref#_formbuilder_mail_media";
        
        $sql[] = "CREATE TABLE IF NOT EXISTS #pref#_formbuilder_mail_media (
  FORMBUILDER_ID int(11) NOT NULL default '0',
  FORMBUILDER_MAIL_TYPE varchar(100) collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_MAIL_MEDIA_ORDER int(11) NOT NULL,
  MEDIA_ID int(11) NOT NULL default '0',
  PRIMARY KEY  (FORMBUILDER_ID,FORMBUILDER_MAIL_TYPE,FORMBUILDER_MAIL_MEDIA_ORDER),
  KEY MEDIA_ID (MEDIA_ID),
  KEY FORMBUILDER_MAIL_TYPE (FORMBUILDER_MAIL_TYPE),
  KEY FORMBUILDER_ID (FORMBUILDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci";
        
        $sql[] = "DROP TABLE IF EXISTS #pref#_formbuilder_value";
        
        $sql[] = "CREATE TABLE IF NOT EXISTS #pref#_formbuilder_value (
  FORMBUILDER_VALUE_ID int(11) NOT NULL auto_increment,
  FORMBUILDER_ID int(11) NOT NULL,
  FORMBUILDER_VALUE_DATA longtext collate utf8_swedish_ci NOT NULL,
  FORMBUILDER_VALUE_STRUCTURE longtext collate utf8_swedish_ci NOT NULL,
  PRIMARY KEY  (FORMBUILDER_VALUE_ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci";
        
        $sql[] = "REPLACE INTO `#pref#_label` (`LABEL_ID`, `LABEL_INFO`) VALUES
('FORMBUILDER_ADD_FIELD', NULL),
('FORMBUILDER_ADD_FIELD_SETTING', NULL),
('FORMBUILDER_ADD_FORM_SETTING', NULL),
('FORMBUILDER_CANCEL', NULL),
('FORMBUILDER_CLOSE_MSG', NULL),
('FORMBUILDER_CSS', NULL),
('FORMBUILDER_DEL', NULL),
('FORMBUILDER_DESC', NULL),
('FORMBUILDER_EDIT', NULL),
('FORMBUILDER_EDITOR', NULL),
('FORMBUILDER_FORMCHOICE', NULL),
('FORMBUILDER_ID', NULL),
('FORMBUILDER_LABEL', NULL),
('FORMBUILDER_LABEL_ADDACHOICE', NULL),
('FORMBUILDER_LABEL_CHOICES', NULL),
('FORMBUILDER_LABEL_CIVILITY_CHECKBOX', NULL),
('FORMBUILDER_LABEL_CIVILITY_COMBO', NULL),
('FORMBUILDER_LABEL_CODE', NULL),
('FORMBUILDER_LABEL_DESCRIPTION', NULL),
('FORMBUILDER_LABEL_INSTRUCTIONS', NULL),
('FORMBUILDER_LABEL_MLLE', NULL),
('FORMBUILDER_LABEL_MME', NULL),
('FORMBUILDER_LABEL_MR', NULL),
('FORMBUILDER_LABEL_NAME', NULL),
('FORMBUILDER_LABEL_RANDOMIZED?', NULL),
('FORMBUILDER_LABEL_REGEXP', NULL),
('FORMBUILDER_LABEL_REGEXP_MSG', NULL),
('FORMBUILDER_LABEL_REGEXP_SAMPLE', NULL),
('FORMBUILDER_LABEL_REQUIRED?', NULL),
('FORMBUILDER_LABEL_RIB_CHECKBOX', NULL),
('FORMBUILDER_LABEL_RIB_COMBO', NULL),
('FORMBUILDER_LABEL_SUCCESS', NULL),
('FORMBUILDER_LABEL_TITLE', NULL),
('FORMBUILDER_LABEL_TYPE', NULL),
('FORMBUILDER_LANGUAGE', NULL),
('FORMBUILDER_MAIL_BODY_HTML', NULL),
('FORMBUILDER_MAIL_BODY_TEXT', NULL),
('FORMBUILDER_MAIL_BODY_TYPE', NULL),
('FORMBUILDER_MAIL_BODY_TYPE_HTML', NULL),
('FORMBUILDER_MAIL_BODY_TYPE_TEXT', NULL),
('FORMBUILDER_MAIL_CC', NULL),
('FORMBUILDER_MAIL_CCI', NULL),
('FORMBUILDER_MAIL_DEST', NULL),
('FORMBUILDER_MAIL_EXP', NULL),
('FORMBUILDER_MAIL_FILE', NULL),
('FORMBUILDER_MAIL_SUBJECT', NULL),
('FORMBUILDER_MODE', NULL),
('FORMBUILDER_MODULE', NULL),
('FORMBUILDER_NAME', NULL),
('FORMBUILDER_OK', NULL),
('FORMBUILDER_OPTION_CIVILITY_MR', NULL),
('FORMBUILDER_OPTION_CIVILITY_MRS', NULL),
('FORMBUILDER_OPTION_CIVILITY_MS', NULL),
('FORMBUILDER_SMTP_HOST', NULL),
('FORMBUILDER_SMTP_PWD', NULL),
('FORMBUILDER_SMTP_USER', NULL),
('FORMBUILDER_TAB_CSS', NULL),
('FORMBUILDER_TAB_EMAIL', NULL),
('FORMBUILDER_TAB_EXTENDED_EMAIL', NULL),
('FORMBUILDER_TAB_GLOBAL', NULL),
('FORMBUILDER_TITLE', NULL),
('FORMBUILDER_TITLE_CHECK', NULL),
('FORMBUILDER_TITLE_CIVILITY', NULL),
('FORMBUILDER_TITLE_FIRSTCHOICE', NULL),
('FORMBUILDER_TITLE_FIRSTFIELD', NULL),
('FORMBUILDER_TITLE_IBAN', NULL),
('FORMBUILDER_TITLE_NAME', NULL),
('FORMBUILDER_TITLE_NUMBER', NULL),
('FORMBUILDER_TITLE_PHONE', NULL),
('FORMBUILDER_TITLE_RIB', NULL),
('FORMBUILDER_TITLE_SECONDCHOICE', NULL),
('FORMBUILDER_TITLE_SECTIONBREAK', NULL),
('FORMBUILDER_TITLE_SECTIONDESC', NULL),
('FORMBUILDER_TITLE_SELECTACHOICE', NULL),
('FORMBUILDER_TITLE_SUBMIT', NULL),
('FORMBUILDER_TITLE_TEXT', NULL),
('FORMBUILDER_TITLE_TEXTAREA', NULL),
('FORMBUILDER_TITLE_THIRDCHOICE', NULL),
('FORMBUILDER_TITLE_UNTITLED', NULL),
('FORMBUILDER_TXT_CREATEAFIELD', NULL),
('FORMBUILDER_TXT_NOFIELD', NULL),
('FORMBUILDER_TXT_SELECTAFIELD', NULL),
('FORMBUILDER_TYPE_ADDRESS', NULL),
('FORMBUILDER_TYPE_ADMIN', NULL),
('FORMBUILDER_TYPE_CAPTCHA', NULL),
('FORMBUILDER_TYPE_CHECKBOXES', NULL),
('FORMBUILDER_TYPE_CIVILITY', NULL),
('FORMBUILDER_TYPE_CLIENT', NULL),
('FORMBUILDER_TYPE_DATE', NULL),
('FORMBUILDER_TYPE_DROPDOWN', NULL),
('FORMBUILDER_TYPE_EMAIL', NULL),
('FORMBUILDER_TYPE_FILE_UPLOAD', NULL),
('FORMBUILDER_TYPE_IBAN', NULL),
('FORMBUILDER_TYPE_LIKERT', NULL),
('FORMBUILDER_TYPE_MULTIPLE_CHOICE', NULL),
('FORMBUILDER_TYPE_NAME', NULL),
('FORMBUILDER_TYPE_NUMBER', NULL),
('FORMBUILDER_TYPE_P', NULL),
('FORMBUILDER_TYPE_PAGE_BREAK', NULL),
('FORMBUILDER_TYPE_PARAGRAPH_TEXT', NULL),
('FORMBUILDER_TYPE_PHONE', NULL),
('FORMBUILDER_TYPE_PRICE', NULL),
('FORMBUILDER_TYPE_PROVIDER', NULL),
('FORMBUILDER_TYPE_RIB', NULL),
('FORMBUILDER_TYPE_SECTION_BREAK', NULL),
('FORMBUILDER_TYPE_SINGLE_LINE_TEXT', NULL),
('FORMBUILDER_TYPE_SUBMIT', NULL),
('FORMBUILDER_TYPE_TIME', NULL),
('FORMBUILDER_TYPE_WEBSITE', NULL),
('FORMBUILDER_VALUE', NULL),
('FORMBUILDER_VALUES', NULL)";
        
        $sql[] = "REPLACE INTO `#pref#_label_langue` (`LABEL_ID`, `LANGUE_ID`, `LABEL_TRANSLATE`, `LABEL_PATH`) VALUES
('FORMBUILDER_ADD_FIELD', 1, 'Ajouter un champ', ''),
('FORMBUILDER_ADD_FIELD', 2, 'Add a Field', ''),
('FORMBUILDER_ADD_FIELD', 3, 'Aggiungi campo', ''),
('FORMBUILDER_ADD_FIELD', 4, 'Añadir campo', ''),
('FORMBUILDER_ADD_FIELD', 10, 'Feld hinzufügen', ''),
('FORMBUILDER_ADD_FIELD_SETTING', 1, 'Param. du champ', ''),
('FORMBUILDER_ADD_FIELD_SETTING', 2, 'Field''s Param.', ''),
('FORMBUILDER_ADD_FIELD_SETTING', 3, 'Parametri di campo', ''),
('FORMBUILDER_ADD_FIELD_SETTING', 4, 'Param. campo', ''),
('FORMBUILDER_ADD_FIELD_SETTING', 10, 'Feld parameter', ''),
('FORMBUILDER_ADD_FORM_SETTING', 1, 'Param. du formulaire', ''),
('FORMBUILDER_ADD_FORM_SETTING', 2, 'Form''s Param.', ''),
('FORMBUILDER_ADD_FORM_SETTING', 3, 'Parametri di modulo', ''),
('FORMBUILDER_ADD_FORM_SETTING', 4, 'Los parám. de formulario', ''),
('FORMBUILDER_ADD_FORM_SETTING', 10, 'Form-Parameter', ''),
('FORMBUILDER_CANCEL', 1, 'Annuler', ''),
('FORMBUILDER_CANCEL', 2, 'Cancel', ''),
('FORMBUILDER_CLOSE_MSG', 1, 'Etes-vous sûr(e) de fermer cette fenêtre ?', ''),
('FORMBUILDER_CLOSE_MSG', 2, 'Are you sure to want to close this window?', ''),
('FORMBUILDER_CSS', 1, 'Feuille de style', ''),
('FORMBUILDER_CSS', 2, 'Stylesheet', ''),
('FORMBUILDER_DEL', 1, 'Supprimer', ''),
('FORMBUILDER_DEL', 2, 'Delete', ''),
('FORMBUILDER_DESC', 1, 'Description', ''),
('FORMBUILDER_DESC', 2, 'Description', ''),
('FORMBUILDER_EDIT', 1, 'Modifier', ''),
('FORMBUILDER_EDIT', 2, 'Edit', ''),
('FORMBUILDER_EDITOR', 1, 'Ouvrir l''éditeur', ''),
('FORMBUILDER_EDITOR', 2, 'Open the Form editor', ''),
('FORMBUILDER_EDITOR', 3, 'Aprire l''editor', ''),
('FORMBUILDER_EDITOR', 4, 'Abra el editor', ''),
('FORMBUILDER_EDITOR', 10, 'Öffnen Sie den editor', ''),
('FORMBUILDER_FORMCHOICE', 1, 'Choix du formulaire', ''),
('FORMBUILDER_FORMCHOICE', 2, 'Form choice', ''),
('FORMBUILDER_ID', 1, 'Id', ''),
('FORMBUILDER_ID', 2, 'Id', ''),
('FORMBUILDER_LABEL', 1, 'Libellé', ''),
('FORMBUILDER_LABEL', 2, 'Label', ''),
('FORMBUILDER_LABEL_ADDACHOICE', 1, 'Ajouter un choix', ''),
('FORMBUILDER_LABEL_ADDACHOICE', 2, 'Add a choice', ''),
('FORMBUILDER_LABEL_CHOICES', 1, 'Choix', ''),
('FORMBUILDER_LABEL_CHOICES', 2, 'Choice', ''),
('FORMBUILDER_LABEL_CODE', 1, 'Code', ''),
('FORMBUILDER_LABEL_CODE', 2, 'Code', ''),
('FORMBUILDER_LABEL_DESCRIPTION', 1, 'Description', ''),
('FORMBUILDER_LABEL_DESCRIPTION', 2, 'Description', ''),
('FORMBUILDER_LABEL_INSTRUCTIONS', 1, 'Instructions', ''),
('FORMBUILDER_LABEL_INSTRUCTIONS', 2, 'Instructions', ''),
('FORMBUILDER_LABEL_MLLE', 1, 'Mademoiselle', ''),
('FORMBUILDER_LABEL_MLLE', 2, 'Miss', ''),
('FORMBUILDER_LABEL_MME', 1, 'Madame', ''),
('FORMBUILDER_LABEL_MME', 2, 'Mrs', ''),
('FORMBUILDER_LABEL_MR', 1, 'Monsieur', ''),
('FORMBUILDER_LABEL_MR', 2, 'Mr', ''),
('FORMBUILDER_LABEL_NAME', 1, 'Nom', ''),
('FORMBUILDER_LABEL_NAME', 2, 'Name', ''),
('FORMBUILDER_LABEL_RANDOMIZED?', 1, 'Aléatoire ?', ''),
('FORMBUILDER_LABEL_RANDOMIZED?', 2, 'Random?', ''),
('FORMBUILDER_LABEL_REGEXP', 1, 'Contrôle de saisie : Expression régulière', ''),
('FORMBUILDER_LABEL_REGEXP', 2, 'Input control : Regexp', ''),
('FORMBUILDER_LABEL_REGEXP_MSG', 1, 'Contrôle de saisie : Message d''erreur', ''),
('FORMBUILDER_LABEL_REGEXP_MSG', 2, 'Input control : Error message', ''),
('FORMBUILDER_LABEL_REGEXP_SAMPLE', 1, 'Exemples', ''),
('FORMBUILDER_LABEL_REGEXP_SAMPLE', 2, 'Samples', ''),
('FORMBUILDER_LABEL_REQUIRED?', 1, 'Obligatoire ?', ''),
('FORMBUILDER_LABEL_REQUIRED?', 2, 'Required?', ''),
('FORMBUILDER_LABEL_SUCCESS', 1, 'Message de confirmation', ''),
('FORMBUILDER_LABEL_SUCCESS', 2, 'Confirmation message', ''),
('FORMBUILDER_LABEL_SUCCESS', 3, 'Messaggio di confirmatione', ''),
('FORMBUILDER_LABEL_SUCCESS', 4, 'Mensaje Confirmación', ''),
('FORMBUILDER_LABEL_TITLE', 1, 'Titre', ''),
('FORMBUILDER_LABEL_TITLE', 2, 'Title', ''),
('FORMBUILDER_LABEL_TYPE', 1, 'Type', ''),
('FORMBUILDER_LABEL_TYPE', 2, 'Type', ''),
('FORMBUILDER_LANGUAGE', 1, 'Langue', ''),
('FORMBUILDER_LANGUAGE', 2, 'Language', ''),
('FORMBUILDER_MAIL_BODY_HTML', 1, 'Format HTML', ''),
('FORMBUILDER_MAIL_BODY_HTML', 2, 'HTML Format', ''),
('FORMBUILDER_MAIL_BODY_TEXT', 1, 'Format Texte', ''),
('FORMBUILDER_MAIL_BODY_TEXT', 2, 'Text Format', ''),
('FORMBUILDER_MAIL_BODY_TYPE', 1, 'Format de mail', ''),
('FORMBUILDER_MAIL_BODY_TYPE', 2, 'Mail format', ''),
('FORMBUILDER_MAIL_BODY_TYPE_HTML', 1, 'HTML', ''),
('FORMBUILDER_MAIL_BODY_TYPE_HTML', 2, 'HTML', ''),
('FORMBUILDER_MAIL_BODY_TYPE_TEXT', 1, 'Texte', ''),
('FORMBUILDER_MAIL_BODY_TYPE_TEXT', 2, 'Text', ''),
('FORMBUILDER_MAIL_CC', 1, 'CC', ''),
('FORMBUILDER_MAIL_CC', 2, 'CC', ''),
('FORMBUILDER_MAIL_CCI', 1, 'CCi', ''),
('FORMBUILDER_MAIL_CCI', 2, 'CCi', ''),
('FORMBUILDER_MAIL_DEST', 1, 'A', ''),
('FORMBUILDER_MAIL_DEST', 2, 'To', ''),
('FORMBUILDER_MAIL_EXP', 1, 'De', ''),
('FORMBUILDER_MAIL_EXP', 2, 'From', ''),
('FORMBUILDER_MAIL_FILE', 1, 'Pièce jointe', ''),
('FORMBUILDER_MAIL_FILE', 2, 'Attachment', ''),
('FORMBUILDER_MAIL_SUBJECT', 1, 'Objet', ''),
('FORMBUILDER_MAIL_SUBJECT', 2, 'Subject', ''),
('FORMBUILDER_MODE', 1, 'Mode', ''),
('FORMBUILDER_MODE', 2, 'Submit mode', ''),
('FORMBUILDER_MODULE', 1, 'Formbuilder', ''),
('FORMBUILDER_MODULE', 2, 'Formbuilder', ''),
('FORMBUILDER_NAME', 1, 'Nom', ''),
('FORMBUILDER_NAME', 2, 'Name', ''),
('FORMBUILDER_OK', 1, 'Valider', ''),
('FORMBUILDER_OK', 2, 'Save', ''),
('FORMBUILDER_OPTION_CIVILITY_MR', 1, 'Monsieur', ''),
('FORMBUILDER_OPTION_CIVILITY_MR', 2, 'Mr', ''),
('FORMBUILDER_OPTION_CIVILITY_MRS', 1, 'Madame', ''),
('FORMBUILDER_OPTION_CIVILITY_MRS', 2, 'Mrs', ''),
('FORMBUILDER_OPTION_CIVILITY_MS', 1, 'Mademoiselle', ''),
('FORMBUILDER_OPTION_CIVILITY_MS', 2, 'Miss', ''),
('FORMBUILDER_SMTP_HOST', 1, 'Serveur SMTP', ''),
('FORMBUILDER_SMTP_HOST', 2, 'SMTP Server', ''),
('FORMBUILDER_SMTP_PWD', 1, 'Mot de passe SMTP', ''),
('FORMBUILDER_SMTP_PWD', 2, 'SMTP password', ''),
('FORMBUILDER_SMTP_USER', 1, 'Nom d''utilisateur SMTP', ''),
('FORMBUILDER_SMTP_USER', 2, 'SMTP username', ''),
('FORMBUILDER_TAB_CSS', 1, 'Feuille de style', ''),
('FORMBUILDER_TAB_CSS', 2, 'StyleSheet', ''),
('FORMBUILDER_TAB_EMAIL', 1, 'Mail', ''),
('FORMBUILDER_TAB_EMAIL', 2, 'Mail', ''),
('FORMBUILDER_TAB_EXTENDED_EMAIL', 1, 'SMTP', ''),
('FORMBUILDER_TAB_EXTENDED_EMAIL', 2, 'SMTP', ''),
('FORMBUILDER_TAB_GLOBAL', 1, 'Général', ''),
('FORMBUILDER_TAB_GLOBAL', 2, 'General', ''),
('FORMBUILDER_TITLE', 1, 'Titre', ''),
('FORMBUILDER_TITLE', 2, 'Title', ''),
('FORMBUILDER_TITLE_CHECK', 1, 'Cocher', ''),
('FORMBUILDER_TITLE_CHECK', 2, 'Check', ''),
('FORMBUILDER_TITLE_CIVILITY', 1, 'Civilité', ''),
('FORMBUILDER_TITLE_CIVILITY', 2, 'Civility', ''),
('FORMBUILDER_TITLE_FIRSTCHOICE', 1, '1er choix', ''),
('FORMBUILDER_TITLE_FIRSTCHOICE', 2, '1st choice', ''),
('FORMBUILDER_TITLE_FIRSTFIELD', 1, 'Premier champ', ''),
('FORMBUILDER_TITLE_FIRSTFIELD', 2, 'First field', ''),
('FORMBUILDER_TITLE_IBAN', 1, 'IBAN', ''),
('FORMBUILDER_TITLE_IBAN', 2, 'IBAN', ''),
('FORMBUILDER_TITLE_NAME', 1, 'Nom', ''),
('FORMBUILDER_TITLE_NAME', 2, 'Name', ''),
('FORMBUILDER_TITLE_NUMBER', 1, 'Nombre', ''),
('FORMBUILDER_TITLE_NUMBER', 2, 'Number', ''),
('FORMBUILDER_TITLE_PHONE', 1, 'Téléphone', ''),
('FORMBUILDER_TITLE_PHONE', 2, 'Phone', ''),
('FORMBUILDER_TITLE_RIB', 1, 'RIB', ''),
('FORMBUILDER_TITLE_RIB', 2, 'RIB', ''),
('FORMBUILDER_TITLE_SECONDCHOICE', 1, '2nd choix', ''),
('FORMBUILDER_TITLE_SECONDCHOICE', 2, '2nd choice', ''),
('FORMBUILDER_TITLE_SECTIONBREAK', 1, 'Titre de paragraphe', ''),
('FORMBUILDER_TITLE_SECTIONBREAK', 2, 'Paragraph title', ''),
('FORMBUILDER_TITLE_SECTIONDESC', 1, 'Contenu du paragraphe', ''),
('FORMBUILDER_TITLE_SECTIONDESC', 2, 'Paragraph content', ''),
('FORMBUILDER_TITLE_SELECTACHOICE', 1, 'Sélectionner un choix', ''),
('FORMBUILDER_TITLE_SELECTACHOICE', 2, 'Select a choice', ''),
('FORMBUILDER_TITLE_SUBMIT', 1, 'Valider', ''),
('FORMBUILDER_TITLE_SUBMIT', 2, 'Ok', ''),
('FORMBUILDER_TITLE_TEXT', 1, 'Texte', ''),
('FORMBUILDER_TITLE_TEXT', 2, 'Text', ''),
('FORMBUILDER_TITLE_TEXTAREA', 1, 'Paragraphe', ''),
('FORMBUILDER_TITLE_TEXTAREA', 2, 'Texarea', ''),
('FORMBUILDER_TITLE_THIRDCHOICE', 1, '3ème choix', ''),
('FORMBUILDER_TITLE_THIRDCHOICE', 2, '3rd choice', ''),
('FORMBUILDER_TITLE_UNTITLED', 1, 'Sans titre', ''),
('FORMBUILDER_TITLE_UNTITLED', 2, 'Untitled', ''),
('FORMBUILDER_TXT_CREATEAFIELD', 1, 'Créer un champ', ''),
('FORMBUILDER_TXT_CREATEAFIELD', 2, 'Create a field', ''),
('FORMBUILDER_TXT_NOFIELD', 1, 'Aucun champ de défini', ''),
('FORMBUILDER_TXT_NOFIELD', 2, 'No field defined', ''),
('FORMBUILDER_TXT_SELECTAFIELD', 1, 'Sélectionner un champ', ''),
('FORMBUILDER_TXT_SELECTAFIELD', 2, 'Select a field', ''),
('FORMBUILDER_TYPE_ADDRESS', 1, 'Adresse', ''),
('FORMBUILDER_TYPE_ADDRESS', 2, 'Address', ''),
('FORMBUILDER_TYPE_ADMIN', 1, 'Gestionnaire', ''),
('FORMBUILDER_TYPE_ADMIN', 2, 'Admin', ''),
('FORMBUILDER_TYPE_CAPTCHA', 1, 'Captcha', ''),
('FORMBUILDER_TYPE_CAPTCHA', 2, 'Captcha', ''),
('FORMBUILDER_TYPE_CHECKBOXES', 1, 'Cases à cocher', ''),
('FORMBUILDER_TYPE_CHECKBOXES', 2, 'Checkboxes', ''),
('FORMBUILDER_TYPE_CIVILITY', 1, 'Civilité', ''),
('FORMBUILDER_TYPE_CIVILITY', 2, 'Civility', ''),
('FORMBUILDER_TYPE_CLIENT', 1, 'Client', ''),
('FORMBUILDER_TYPE_CLIENT', 2, 'Customer', ''),
('FORMBUILDER_TYPE_DATE', 1, 'Date', ''),
('FORMBUILDER_TYPE_DATE', 2, 'Date', ''),
('FORMBUILDER_TYPE_DROPDOWN', 1, 'Liste déroulante', ''),
('FORMBUILDER_TYPE_DROPDOWN', 2, 'Combo', ''),
('FORMBUILDER_TYPE_EMAIL', 1, 'Email', ''),
('FORMBUILDER_TYPE_EMAIL', 2, 'E-mail', ''),
('FORMBUILDER_TYPE_FILE_UPLOAD', 1, 'Upload', ''),
('FORMBUILDER_TYPE_FILE_UPLOAD', 2, 'Upload', ''),
('FORMBUILDER_TYPE_IBAN', 1, 'IBAN', ''),
('FORMBUILDER_TYPE_IBAN', 2, 'IBAN', ''),
('FORMBUILDER_TYPE_LIKERT', 1, 'Likert', ''),
('FORMBUILDER_TYPE_LIKERT', 2, 'Likert', ''),
('FORMBUILDER_TYPE_MULTIPLE_CHOICE', 1, 'Choix multiple', ''),
('FORMBUILDER_TYPE_MULTIPLE_CHOICE', 2, 'Multiple choice', ''),
('FORMBUILDER_TYPE_NAME', 1, 'Nom', ''),
('FORMBUILDER_TYPE_NAME', 2, 'Name', ''),
('FORMBUILDER_TYPE_NUMBER', 1, 'Nombre', ''),
('FORMBUILDER_TYPE_NUMBER', 2, 'Number', ''),
('FORMBUILDER_TYPE_P', 1, 'Texte libre', ''),
('FORMBUILDER_TYPE_P', 2, 'Free text', ''),
('FORMBUILDER_TYPE_PAGE_BREAK', 1, 'Saut de page', ''),
('FORMBUILDER_TYPE_PAGE_BREAK', 2, 'Page break', ''),
('FORMBUILDER_TYPE_PARAGRAPH_TEXT', 1, 'Paragraphe', ''),
('FORMBUILDER_TYPE_PARAGRAPH_TEXT', 2, 'Paragraph', ''),
('FORMBUILDER_TYPE_PHONE', 1, 'Téléphone', ''),
('FORMBUILDER_TYPE_PHONE', 2, 'Phone number', ''),
('FORMBUILDER_TYPE_PRICE', 1, 'Prix', ''),
('FORMBUILDER_TYPE_PRICE', 2, 'Price', ''),
('FORMBUILDER_TYPE_PROVIDER', 1, 'Fournisseur', ''),
('FORMBUILDER_TYPE_PROVIDER', 2, 'Provider', ''),
('FORMBUILDER_TYPE_RIB', 1, 'RIB', ''),
('FORMBUILDER_TYPE_RIB', 2, 'RIB', ''),
('FORMBUILDER_TYPE_SECTION_BREAK', 1, 'Texte libre', ''),
('FORMBUILDER_TYPE_SECTION_BREAK', 2, 'Free text', ''),
('FORMBUILDER_TYPE_SINGLE_LINE_TEXT', 1, 'Texte simple', ''),
('FORMBUILDER_TYPE_SINGLE_LINE_TEXT', 2, 'Plain text', ''),
('FORMBUILDER_TYPE_SUBMIT', 1, 'Bouton de validation', ''),
('FORMBUILDER_TYPE_SUBMIT', 2, 'Submit button', ''),
('FORMBUILDER_TYPE_TIME', 1, 'Heure', ''),
('FORMBUILDER_TYPE_TIME', 2, 'Time', ''),
('FORMBUILDER_TYPE_WEBSITE', 1, 'SIte web', ''),
('FORMBUILDER_TYPE_WEBSITE', 2, 'Web SIte', ''),
('FORMBUILDER_VALUE', 1, 'Valeur', ''),
('FORMBUILDER_VALUES', 1, 'Valeurs', ''),
('FORMBUILDER_VALUES', 2, 'Values', '')";
        
        foreach ($sql as $query) {
            $oConnection->query($query);
        }
    }

    /**
     * Ã  lancer lors de la dÃ©sinstatllation
     * - suppression de tables
     * - suppression de donnÃ©es
     */
    public function uninstall ()
    {
        $oConnection = Pelican_Db::getInstance();
        
        $sql[] = "DROP TABLE IF EXISTS #pref#_formbuilder";
        $sql[] = "DROP TABLE IF EXISTS #pref#_formbuilder_mail";
        $sql[] = "DROP TABLE IF EXISTS #pref#_formbuilder_mail_media";
        $sql[] = "DROP TABLE IF EXISTS #pref#_formbuilder_value";
        $sql[] = "DELETE FROM `#pref#_label_langue` WHERE `LABEL_ID` LIKE 'FORMBUILDER%'";
        $sql[] = "DELETE FROM `#pref#_label` WHERE `LABEL_ID` LIKE 'FORMBUILDER%'";
        
        foreach ($sql as $query) {
            $oConnection->query($query);
        }
    }
}