<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp200409="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsp200607="http://www.w3.org/2006/07/ws-policy" xmlns:ns0="http://xml.inetpsa.com/Services/Cfg/EngineCriteria" targetNamespace="http://xml.inetpsa.com/Services/Cfg/EngineCriteria">
<wsdl:types xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:schema>
<xsd:import schemaLocation="EngineCriteria.xsd3.xsd" namespace="http://xml.inetpsa.com/Services/Cfg/EngineCriteria"/></xsd:schema></wsdl:types>
<wsdl:message name="EngineCriteriaRequest">
<wsdl:part name="parameters" element="xsns:EngineCriteria" xmlns:xsns="http://xml.inetpsa.com/Services/Cfg/EngineCriteria"/></wsdl:message>
<wsdl:message name="EngineCriteriaResponse">
<wsdl:part name="parameters" element="xsns:EngineCriteriaResponse" xmlns:xsns="http://xml.inetpsa.com/Services/Cfg/EngineCriteria"/></wsdl:message>
<wsdl:message name="ServiceException">
<wsdl:part name="ServiceException" element="xsns:ServiceException" xmlns:xsns="http://xml.inetpsa.com/Services/Cfg/EngineCriteria"/></wsdl:message>
<wsdl:portType name="EngineCriteriaPortType">
<wsdl:operation name="EngineCriteria">
<wsdl:input name="EngineCriteriaRequest" message="ns0:EngineCriteriaRequest"/>
<wsdl:output name="EngineCriteriaResponse" message="ns0:EngineCriteriaResponse"/>
<wsdl:fault name="ServiceException" message="ns0:ServiceException"/></wsdl:operation></wsdl:portType>
<wsdl:binding name="EngineCriteriaHttpBinding" type="ns0:EngineCriteriaPortType">
<soap11:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<wsdl:operation name="EngineCriteria">
<soap11:operation soapAction="http://xml.inetpsa.com/Services/Cfg/EngineCriteria#EngineCriteria" style="document"/>
<wsdl:input name="EngineCriteriaRequest">
<soap11:body use="literal"/></wsdl:input>
<wsdl:output name="EngineCriteriaResponse">
<soap11:body use="literal"/></wsdl:output>
<wsdl:fault name="ServiceException">
<soap11:fault name="ServiceException" use="literal"/></wsdl:fault></wsdl:operation></wsdl:binding>
<wsdl:service name="EngineCriteria">
<wsdl:port name="EngineCriteriaHttpPort.0" binding="ns0:EngineCriteriaHttpBinding">
<soap11:address location="http://10.68.110.80:80/cfg/services/EngineCriteria"/></wsdl:port>
<wsdl:port name="EngineCriteriaHttpPort.1" binding="ns0:EngineCriteriaHttpBinding">
<soap11:address location="http://10.68.110.80:80/cfg/pub/services/EngineCriteria"/></wsdl:port></wsdl:service></wsdl:definitions>