-- migration Version20150420161520
 INSERT INTO `psa_label` (`LABEL_ID`, `LABEL_INFO`, `LABEL_BACK`, `LABEL_LENGTH`, `LABEL_CASE`, `LABEL_BO`, `LABEL_FO`) VALUES
                 ("NDP_CINEMASCOPE", NULL, 2, NULL, NULL, 1, NULL),
                ("NDP_TIMING_SLIDE", NULL, 2, NULL, NULL, 1, NULL),
                ("NDP_TOGGLE", NULL, 2, NULL, NULL, 1, NULL),
                ("NDP_MSG_TOGGLE", NULL, 2, NULL, NULL, 1, NULL),
                ("NDP_DISPLAY_FICHE_SERVICE", NULL, 2, NULL, NULL, 1, NULL);
INSERT INTO `psa_label_langue_site` (`LABEL_ID`, `LANGUE_ID`, `SITE_ID`, `LABEL_TRANSLATE`) VALUES
                ("NDP_CINEMASCOPE", 1, 1, "Visuel cinemascope"),
                ("NDP_TIMING_SLIDE", 1, 1, "Temps défilement du diaporama en seconde"),
                ("NDP_TOGGLE", 1, 1, "Libellé toggle"),
                ("NDP_MSG_TOGGLE", 1, 1, "Mode d\'ouverture des toggles à l\'arrivée sur la page :"),
                ("NDP_DISPLAY_FICHE_SERVICE", 1, 1, "Affichage fiche service showroom");

-- migration Version20150420162646
INSERT INTO psa_media_type (MEDIA_TYPE_ID, MEDIA_TYPE_LABEL) VALUES ('streamlike', 'Streamlike');

ALTER TABLE psa_site ADD STREAMLIKE_CACHETIME INT NULL;

INSERT INTO psa_label (LABEL_ID, LABEL_INFO, LABEL_BACK, LABEL_LENGTH, LABEL_CASE, LABEL_BO, LABEL_FO) VALUES
                ('MEDIA_TYPE_STREAMLIKE', NULL, 2, NULL, NULL, 1, NULL),
                ('MEDIA_RATIO', NULL, 2, NULL, NULL, 1, NULL),
                ('MEDIA_CREDITS', NULL, 2, NULL, NULL, 1, NULL),
                ('DATE_UPDATE', NULL, 2, NULL, NULL, 1, NULL),
                ('MEDIA_VISIBILITY', NULL, 2, NULL, NULL, 1, NULL),
                ('STREAMLIKE_COMPANY_ID', NULL, 2, NULL, NULL, 1, NULL),
                ('STREAMLIKE_CACHETIME', NULL, 2, NULL, NULL, 1, NULL);

INSERT INTO psa_label_langue_site (LABEL_ID, LANGUE_ID, SITE_ID, LABEL_TRANSLATE) VALUES
            ('MEDIA_TYPE_STREAMLIKE', 1, 1, 'Streamlike'),
            ('MEDIA_RATIO', 1, 1, 'Ratio'),
            ('MEDIA_CREDITS', 1, 1, 'Crédits'),
            ('DATE_UPDATE', 1, 1, 'Mise à jour'),
            ('MEDIA_VISIBILITY', 1, 1, 'visibilité'),
            ('STREAMLIKE_COMPANY_ID', 1, 1, 'Streamlike company_id.'),
            ('STREAMLIKE_CACHETIME', 1, 1, 'Streamlike Durée cache (en min)');

-- migration Version20150420180310
UPDATE  psa_site SET  STREAMLIKE_COMPANY_ID =  'f33723b964c0ca5b',
            STREAMLIKE_CACHETIME =  1 WHERE  SITE_ID =2;

-- migration Version20150421170001
INSERT INTO psa_label (LABEL_ID, LABEL_INFO, LABEL_BACK, LABEL_LENGTH, LABEL_CASE, LABEL_BO, LABEL_FO) VALUES
                ('SEARCH_STREAMLIKE_ID', NULL, 2, NULL, NULL, 1, NULL),
                ('SEARCH_STREAMLIKE_KEYWORD', NULL, 2, NULL, NULL, 1, NULL);

INSERT INTO psa_label_langue_site (LABEL_ID, LANGUE_ID, SITE_ID, LABEL_TRANSLATE) VALUES
            ('SEARCH_STREAMLIKE_KEYWORD', 1, 1, 'Mot clé Streamlike'),
            ('SEARCH_STREAMLIKE_ID', 1, 1, 'Recherche par id Streamlike');

-- migration Version20150421171746
INSERT INTO psa_label (LABEL_ID, LABEL_INFO, LABEL_BACK, LABEL_LENGTH, LABEL_CASE, LABEL_BO, LABEL_FO) VALUES
                ('NPD_AFFICHAGE_VISUEL', NULL, 2, NULL, NULL, 1, NULL),
                ('NPD_A_GAUCHE_DU_TEXTE', NULL, 2, NULL, NULL, 1, NULL),
                ('NPD_A_DROITE_DU_TEXTE', NULL, 2, NULL, NULL, 1, NULL),
                ('CTA_VISUEL', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_CTA', NULL, 2, NULL, NULL, 1, NULL);

INSERT INTO psa_label_langue_site (LABEL_ID, LANGUE_ID, SITE_ID, LABEL_TRANSLATE) VALUES
            ('NPD_AFFICHAGE_VISUEL', 1, 1, 'Affichage de visuel'),
            ('NPD_A_GAUCHE_DU_TEXTE', 1, 1, 'A gauche du texte'),
            ('NPD_A_DROITE_DU_TEXTE', 1, 1, 'A droite du texte'),
            ('CTA_VISUEL', 1, 1, 'Visuel CTA'),
            ('NDP_CTA', 1, 1, 'CTA');

UPDATE psa_label_langue_site SET LABEL_TRANSLATE = 'Ajouter' WHERE LABEL_ID ='FORM_BUTTON_ADD_MULTI' AND SITE_ID = 1 AND LANGUE_ID = 1;

-- migration Version20150422110752 : alreaddy delivered in 2015-04-22-migrations.sql

-- migration Version20150423174025

DROP TABLE IF EXISTS psa_page_zone_cta_cta;
CREATE TABLE psa_page_zone_cta_cta (PAGE_ZONE_CTA_CTA_ID INT NOT NULL, PAGE_ZONE_CTA_ID INT NOT NULL, PAGE_ID INT NOT NULL, LANGUE_ID INT NOT NULL, PAGE_VERSION INT NOT NULL, ZONE_TEMPLATE_ID INT NOT NULL, PAGE_ZONE_CTA_STATUS INT DEFAULT NULL, PAGE_ZONE_CTA_TYPE VARCHAR(50) NOT NULL, PAGE_ZONE_CTA_ORDER INT DEFAULT NULL, PAGE_ZONE_CTA_LABEL VARCHAR(50) DEFAULT NULL, DESCRIPTION LONGTEXT DEFAULT NULL, TARGET VARCHAR(50) NOT NULL, STYLE VARCHAR(50) NOT NULL, CTA_REF_TYPE VARCHAR(50) NOT NULL, CTA_ID INT NOT NULL, INDEX IDX_A5907A9EB4EDB1E5622E2C229381310F15EAE15 (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID), INDEX IDX_A5907A9EE1DF977A (CTA_ID), INDEX IDX_A5907A9EB4EDB1E5622E2C2 (PAGE_ID, LANGUE_ID), PRIMARY KEY(PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID,PAGE_ZONE_CTA_TYPE)) DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ENGINE = InnoDB;
ALTER TABLE psa_page_zone_cta_cta ADD CONSTRAINT FK_A5907A9EB4EDB1E5622E2C229381310F15EAE15 FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID) REFERENCES psa_page_zone (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID) ON DELETE CASCADE;
ALTER TABLE psa_page_zone_cta_cta ADD CONSTRAINT FK_A5907A9EE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID)  ON DELETE CASCADE;
ALTER TABLE psa_page_zone_cta_cta ADD CONSTRAINT FK_A5907A9EB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID)  ON DELETE CASCADE;

DROP TABLE IF EXISTS psa_page_zone_cta;
CREATE TABLE psa_page_zone_cta (PAGE_ZONE_CTA_ID INT NOT NULL, PAGE_ID INT NOT NULL, LANGUE_ID INT NOT NULL, PAGE_VERSION INT NOT NULL, ZONE_TEMPLATE_ID INT NOT NULL, PAGE_ZONE_CTA_STATUS INT DEFAULT NULL, PAGE_ZONE_CTA_TYPE VARCHAR(50) NOT NULL, PAGE_ZONE_CTA_ORDER INT DEFAULT NULL, PAGE_ZONE_CTA_LABEL VARCHAR(50) DEFAULT NULL, DESCRIPTION LONGTEXT DEFAULT NULL, TARGET VARCHAR(50) NOT NULL, STYLE VARCHAR(50) NOT NULL, CTA_REF_TYPE VARCHAR(50) NOT NULL, CTA_ID INT NOT NULL, INDEX IDX_B03DE77CB4EDB1E5622E2C229381310F15EAE15 (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID), INDEX IDX_B03DE77CE1DF977A (CTA_ID), INDEX IDX_B03DE77CB4EDB1E5622E2C2 (PAGE_ID, LANGUE_ID), PRIMARY KEY(PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID,PAGE_ZONE_CTA_TYPE)) DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ENGINE = InnoDB;
ALTER TABLE psa_page_zone_cta ADD CONSTRAINT FK_B03DE77CB4EDB1E5622E2C229381310F15EAE15 FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID) REFERENCES psa_page_zone (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID) ON DELETE CASCADE;
ALTER TABLE psa_page_zone_cta ADD CONSTRAINT FK_B03DE77CE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE;
ALTER TABLE psa_page_zone_cta ADD CONSTRAINT FK_B03DE77CB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE;

-- migration Version20150423180114

DROP TABLE  IF EXISTS  psa_content_version_cta_cta;
CREATE TABLE psa_content_version_cta_cta (PAGE_ZONE_CTA_CTA_ID INT NOT NULL, PAGE_ZONE_CTA_ID INT NOT NULL, CONTENT_ID INT NOT NULL, LANGUE_ID INT NOT NULL, CONTENT_VERSION INT NOT NULL, PAGE_ZONE_CTA_STATUS INT DEFAULT NULL, PAGE_ZONE_CTA_TYPE VARCHAR(50) NOT NULL, PAGE_ZONE_CTA_ORDER INT DEFAULT NULL, PAGE_ZONE_CTA_LABEL VARCHAR(50) DEFAULT NULL, DESCRIPTION LONGTEXT DEFAULT NULL, TARGET VARCHAR(50) NOT NULL, STYLE VARCHAR(50) NOT NULL, CTA_REF_TYPE VARCHAR(50) NOT NULL, CTA_ID INT NOT NULL, PAGE_ID INT NOT NULL, INDEX IDX_E9138D9BB772F8325622E2C229381310 (CONTENT_ID, LANGUE_ID, CONTENT_VERSION), INDEX IDX_E9138D9BE1DF977A (CTA_ID), INDEX IDX_E9138D9BB4EDB1E5622E2C2 (PAGE_ID, LANGUE_ID), PRIMARY KEY(PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, CONTENT_ID, LANGUE_ID, CONTENT_VERSION, PAGE_ZONE_CTA_TYPE)) DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ENGINE = InnoDB;
ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BB772F8325622E2C229381310 FOREIGN KEY (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) REFERENCES psa_content_version (CONTENT_ID, LANGUE_ID, CONTENT_VERSION)  ON DELETE CASCADE;
ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID)  ON DELETE CASCADE;
ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID)  ON DELETE CASCADE;

--  migration Version20150424141009

ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37B4EDB1E5622E2C229381310BA07F8665F342437;
ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37B4EDB1E5622E2C2;
ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37E1DF977A;
DROP INDEX IDX_F83E37B4EDB1E5622E2C229381310BA07F8665F342437 ON psa_page_multi_zone_multi_cta_cta;
ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD PAGE_ZONE_MULTI_ID INT NOT NULL, ADD PAGE_ZONE_MULTI_TYPE VARCHAR(100) NOT NULL;
ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DFAC FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_multi_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE;
ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE;
ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE;
CREATE INDEX IDX_F83E37B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DFA ON psa_page_multi_zone_multi_cta_cta (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE);

ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CB4EDB1E5622E2C2;
ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CB4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6;
ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CE1DF977A;
ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE;
ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CB4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6 FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE;
ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE;
ALTER TABLE psa_page_zone_multi_cta DROP PRIMARY KEY, ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE, PAGE_ZONE_CTA_TYPE);

ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385B772F8325622E2C229381310;
ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385B4EDB1E5622E2C2;
ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385E1DF977A;
DROP INDEX IDX_A5107385B772F8325622E2C229381310 ON psa_content_version_cta;
ALTER TABLE psa_content_version_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL, CHANGE page_version CONTENT_VERSION INT NOT NULL;
ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385B772F8325622E2C2FA8F2C85 FOREIGN KEY (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) REFERENCES psa_content_version (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) ON DELETE CASCADE;
ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE;
ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE;
CREATE INDEX IDX_A5107385B772F8325622E2C2FA8F2C85 ON psa_content_version_cta (CONTENT_ID, LANGUE_ID, CONTENT_VERSION);
ALTER TABLE psa_content_version_cta DROP PRIMARY KEY, ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, CONTENT_ID, LANGUE_ID, CONTENT_VERSION, PAGE_ZONE_CTA_TYPE);

ALTER TABLE psa_page_zone_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL;

ALTER TABLE psa_page_multi_zone_cta DROP FOREIGN KEY FK_BDC5C30EB4EDB1E5622E2C2;
ALTER TABLE psa_page_multi_zone_cta DROP FOREIGN KEY FK_BDC5C30EE1DF977A;
ALTER TABLE psa_page_multi_zone_cta ADD CONSTRAINT FK_BDC5C30EB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE;
ALTER TABLE psa_page_multi_zone_cta ADD CONSTRAINT FK_BDC5C30EE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE;

ALTER TABLE psa_page_zone_cta_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL;
ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639B4EDB1E5622E2C2;
ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DF;
ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639E1DF977A;
ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE;
ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DF FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_multi_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE;
ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE;

ALTER TABLE psa_content_version_cta_cta DROP FOREIGN KEY FK_E9138D9BB4EDB1E5622E2C2;
ALTER TABLE psa_content_version_cta_cta DROP FOREIGN KEY FK_E9138D9BB772F8325622E2C229381310;
ALTER TABLE psa_content_version_cta_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL;
DROP INDEX idx_e9138d9bb772f8325622e2c229381310 ON psa_content_version_cta_cta;
CREATE INDEX IDX_E9138D9BB772F8325622E2C2FA8F2C85 ON psa_content_version_cta_cta (CONTENT_ID, LANGUE_ID, CONTENT_VERSION);
ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE;
ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BB772F8325622E2C229381310 FOREIGN KEY (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) REFERENCES psa_content_version (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) ON DELETE CASCADE;

ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602B4EDB1E5622E2C2;
ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602B4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6;
ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602E1DF977A;
ALTER TABLE psa_page_zone_multi_cta_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL;
ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE;
ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602B4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6 FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE;
ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE;
ALTER TABLE psa_page_zone_multi_cta_cta DROP PRIMARY KEY, ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE, PAGE_ZONE_CTA_TYPE);

ALTER TABLE psa_page_multi_zone_cta_cta DROP FOREIGN KEY FK_F936EBBDB4EDB1E5622E2C2;
ALTER TABLE psa_page_multi_zone_cta_cta DROP FOREIGN KEY FK_F936EBBDE1DF977A;
ALTER TABLE psa_page_multi_zone_cta_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL;
ALTER TABLE psa_page_multi_zone_cta_cta ADD CONSTRAINT FK_F936EBBDB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE;
ALTER TABLE psa_page_multi_zone_cta_cta ADD CONSTRAINT FK_F936EBBDE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE;
ALTER TABLE psa_page_multi_zone_cta_cta DROP PRIMARY KEY, ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_CTA_TYPE);

-- migration Version20150424185748

ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37E1DF977A;
ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);
ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CE1DF977A;
ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);
ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385E1DF977A;
ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);
ALTER TABLE psa_page_zone_cta DROP FOREIGN KEY FK_B03DE77CE1DF977A;
ALTER TABLE psa_page_zone_cta ADD CONSTRAINT FK_B03DE77CE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);
ALTER TABLE psa_page_multi_zone_cta DROP FOREIGN KEY FK_BDC5C30EE1DF977A;
ALTER TABLE psa_page_multi_zone_cta ADD CONSTRAINT FK_BDC5C30EE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);
ALTER TABLE psa_page_zone_cta_cta DROP FOREIGN KEY FK_A5907A9EE1DF977A;
ALTER TABLE psa_page_zone_cta_cta ADD CONSTRAINT FK_A5907A9EE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);
ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639E1DF977A;
ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);
ALTER TABLE psa_content_version_cta_cta DROP FOREIGN KEY FK_E9138D9BE1DF977A;
ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);
ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602E1DF977A;
ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);
ALTER TABLE psa_page_multi_zone_cta_cta DROP FOREIGN KEY FK_F936EBBDE1DF977A;
ALTER TABLE psa_page_multi_zone_cta_cta ADD CONSTRAINT FK_F936EBBDE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID);

-- migration Version20150427115348

ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP PRIMARY KEY;
ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE);
ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD PAGE_ZONE_CTA_CTA_TYPE VARCHAR(50) NOT NULL;

ALTER TABLE psa_page_zone_multi_cta DROP PRIMARY KEY;
ALTER TABLE psa_page_zone_multi_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE);

ALTER TABLE psa_content_version_cta DROP PRIMARY KEY;
ALTER TABLE psa_content_version_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, CONTENT_ID, LANGUE_ID, CONTENT_VERSION);

ALTER TABLE psa_page_zone_cta DROP PRIMARY KEY;
ALTER TABLE psa_page_zone_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID);

ALTER TABLE psa_page_multi_zone_cta DROP PRIMARY KEY;
ALTER TABLE psa_page_multi_zone_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER);

ALTER TABLE psa_page_zone_cta_cta DROP PRIMARY KEY;
ALTER TABLE psa_page_zone_cta_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID);
ALTER TABLE psa_page_zone_cta_cta ADD PAGE_ZONE_CTA_CTA_TYPE VARCHAR(50) NOT NULL;

ALTER TABLE psa_page_multi_zone_multi_cta DROP PRIMARY KEY;
ALTER TABLE psa_page_multi_zone_multi_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE);

ALTER TABLE psa_content_version_cta_cta DROP PRIMARY KEY;
ALTER TABLE psa_content_version_cta_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, CONTENT_ID, LANGUE_ID, CONTENT_VERSION);
ALTER TABLE psa_content_version_cta_cta ADD PAGE_ZONE_CTA_CTA_TYPE VARCHAR(50) NOT NULL;

ALTER TABLE psa_page_zone_multi_cta_cta DROP PRIMARY KEY;
ALTER TABLE psa_page_zone_multi_cta_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE);
ALTER TABLE psa_page_zone_multi_cta_cta ADD PAGE_ZONE_CTA_CTA_TYPE VARCHAR(50) NOT NULL;

ALTER TABLE psa_page_multi_zone_cta_cta DROP PRIMARY KEY;
ALTER TABLE psa_page_multi_zone_cta_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER);
ALTER TABLE psa_page_multi_zone_cta_cta ADD PAGE_ZONE_CTA_CTA_TYPE VARCHAR(50) NOT NULL;

-- migration Version20150427120813

TRUNCATE TABLE psa_page_multi_zone_multi_cta_cta;
ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E379AD6FB46C7151C14B4EDB1E5622E2C229381310BA07F8665F34243 FOREIGN KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_multi_zone_multi_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE;
CREATE INDEX IDX_F83E379AD6FB46C7151C14B4EDB1E5622E2C229381310BA07F8665F3424 ON psa_page_multi_zone_multi_cta_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE);

TRUNCATE TABLE psa_page_zone_cta_cta;
ALTER TABLE psa_page_zone_cta_cta ADD CONSTRAINT FK_A5907A9E9AD6FB46C7151C14B4EDB1E5622E2C229381310F15EAE15 FOREIGN KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID) REFERENCES psa_page_zone_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID) ON DELETE CASCADE;
CREATE INDEX IDX_A5907A9E9AD6FB46C7151C14B4EDB1E5622E2C229381310F15EAE15 ON psa_page_zone_cta_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID);

TRUNCATE TABLE psa_content_version_cta_cta;
ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9B9AD6FB46C7151C14B772F8325622E2C2FA8F2C85 FOREIGN KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, CONTENT_ID, LANGUE_ID, CONTENT_VERSION) REFERENCES psa_content_version_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, CONTENT_ID, LANGUE_ID, CONTENT_VERSION) ON DELETE CASCADE;
CREATE INDEX IDX_E9138D9B9AD6FB46C7151C14B772F8325622E2C2FA8F2C85 ON psa_content_version_cta_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, CONTENT_ID, LANGUE_ID, CONTENT_VERSION);

TRUNCATE TABLE psa_page_zone_multi_cta_cta;
ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D6029AD6FB46C7151C14B4EDB1E5622E2C229381310F15EAE15F55F4 FOREIGN KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_zone_multi_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE;
CREATE INDEX IDX_6000D6029AD6FB46C7151C14B4EDB1E5622E2C229381310F15EAE15F55F ON psa_page_zone_multi_cta_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE);

TRUNCATE TABLE psa_page_multi_zone_cta_cta;
ALTER TABLE psa_page_multi_zone_cta_cta ADD CONSTRAINT FK_F936EBBD9AD6FB46C7151C14B4EDB1E5622E2C229381310BA07F8665F342 FOREIGN KEY (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER) REFERENCES psa_page_multi_zone_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER) ON DELETE CASCADE;
CREATE INDEX IDX_F936EBBD9AD6FB46C7151C14B4EDB1E5622E2C229381310BA07F8665F34 ON psa_page_multi_zone_cta_cta (PAGE_ZONE_CTA_ID, PAGE_ZONE_CTA_TYPE, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER);

-- migration Version20150427134345 : already delivered in 2015-04-27-migrations.sql

-- migration Version20150427140016
INSERT INTO psa_label (LABEL_ID, LABEL_INFO, LABEL_BACK, LABEL_LENGTH, LABEL_CASE, LABEL_BO, LABEL_FO) VALUES
                ('NDP_CARPICKER_VEHICULES_INFO', NULL, 2, NULL, NULL, 1, NULL),
                ('MODELCAR', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_MODELE', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_CUSTOM_LINK', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_YES', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_NO', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_SHOW_PRICE', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_CTA_CARPICKER', NULL, 2, NULL, NULL, 1, NULL);
INSERT INTO psa_label_langue_site (LABEL_ID, LANGUE_ID, SITE_ID, LABEL_TRANSLATE) VALUES
            ('NDP_CARPICKER_VEHICULES_INFO', 1, 1, 'Ajout maximum de 20 véhicules issus du référentiel modèle dans la rubrique XXX du BO. Sur le mobile seul les 9 premiers véhicules seront affichés.'),
            ('MODELCAR', 1, 1, 'Modèle de véhicules'),
            ('NDP_MODELE', 1, 1, 'Modèle'),
            ('NDP_CUSTOM_LINK', 1, 1, 'Autre URL'),
            ('NDP_YES', 1, 1, 'Oui'),
            ('NDP_NO', 1, 1, 'Non'),
            ('NDP_SHOW_PRICE', 1, 1, 'Afficher les prix'),
            ('NDP_CTA_CARPICKER', 1, 1, 'CTA Car Picker');

-- migration Version20150427144411

UPDATE psa_label_langue_site SET LABEL_TRANSLATE='URL Visuel' WHERE LABEL_ID='URL_VISUEL'  AND SITE_ID = 1 AND LANGUE_ID = 1;

-- migration Version20150427152730

UPDATE psa_label_langue_site SET LABEL_TRANSLATE = 'Titre miniature' WHERE LABEL_ID ='NDP_MINIATURE_TEXT' AND SITE_ID = 1 AND LANGUE_ID = 1;
INSERT INTO psa_label (LABEL_ID, LABEL_INFO, LABEL_BACK, LABEL_LENGTH, LABEL_CASE, LABEL_BO, LABEL_FO) VALUES
                ('ADD_SLIDE_VISUEL', NULL, 2, NULL, NULL, 1, NULL),
                ('ADD_SLIDE_HTML5', NULL, 2, NULL, NULL, 1, NULL),
                ('ADD_SLIDE_VIDEO', NULL, 2, NULL, NULL, 1, NULL),
                ('ADD_CTA_LISTE_DEROULANTE', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_ADD_LIEN', NULL, 2, NULL, NULL, 1, NULL),
                ('PDF', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_ADD_VISUEL', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_TAILLE_VISUEL',  NULL, 2, NULL, NULL, 1, NULL),
                ('AFFICHAGE_FICHE_SERVICE_SHOWROOM', NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_TITRE_ANCRE',  NULL, 2, NULL, NULL, 1, NULL),
                ('ANCHOR',  NULL, 2, NULL, NULL, 1, NULL),
                ('VISUEL_WEB',  NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_VISUEL',  NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_ADD_SLIDE',  NULL, 2, NULL, NULL, 1, NULL),
                ('ALERT_PLAN_MOBILE',  NULL, 2, NULL, NULL, 1, NULL),
                ('ADD_MODELCAR',  NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_ADD_TOGGLE',  NULL, 2, NULL, NULL, 1, NULL),
                ('NDP_ADD_VERBATIM',  NULL, 2, NULL, NULL, 1, NULL);

INSERT INTO psa_label_langue_site (LABEL_ID, LANGUE_ID, SITE_ID, LABEL_TRANSLATE) VALUES
            ('ADD_SLIDE_VISUEL', 1, 1, 'Ajouter un visuel'),
            ('ADD_SLIDE_HTML5', 1, 1,  'Ajouter un bloc HTML'),
            ('ADD_SLIDE_VIDEO', 1, 1,  'Ajouter une vidéo'),
            ('ADD_CTA_LISTE_DEROULANTE', 1, 1, 'Ajouter un CTA à la liste déroulante'),
            ('NDP_ADD_LIEN', 1, 1, 'Ajouter un lien'),
            ('PDF', 1, 1, 'PDF'),
            ('NDP_ADD_VISUEL', 1, 1, 'Ajouter un visuel'),
            ('NDP_TAILLE_VISUEL', 1, 1, 'A gauche du texte'),
            ('AFFICHAGE_FICHE_SERVICE_SHOWROOM', 1, 1, 'Affichage fiche service showroom'),
            ('NDP_TITRE_ANCRE', 1, 1, 'Titre de l\'ancre'),
            ('NDP_VISUEL', 1, 1, 'Visuel'),
            ('ANCHOR', 1, 1, 'Ancre'),
            ('VISUEL_WEB', 1, 1, 'Visuel Web'),
            ('NDP_ADD_SLIDE', 1, 1, 'Ajouter une slide'),
            ('ALERT_PLAN_MOBILE', 1, 1, 'La page plan du site n\'existe pas sur mobile.'),
            ('ADD_MODELCAR', 1, 1, 'Ajouter un modèle'),
            ('NDP_ADD_TOGGLE', 1, 1, 'Visuel'),
            ('NDP_ADD_VERBATIM', 1, 1, 'Ajouter un verbatim');
    UPDATE psa_label_langue_site SET LABEL_TRANSLATE = 'Colonnes' WHERE LABEL_ID ='NDP_COLONNES' AND SITE_ID = 1 AND LANGUE_ID = 1;

-- migration Version20150427172434

UPDATE psa_label_langue_site SET LABEL_TRANSLATE = 'Préconisation : saisir le libellé en majuscules.' WHERE LABEL_ID ='NDP_MSG_PRECO_UPPERCASE_TITLE' AND SITE_ID = 1 AND LANGUE_ID = 1;

INSERT INTO psa_label (LABEL_ID, LABEL_INFO, LABEL_BACK, LABEL_LENGTH, LABEL_CASE, LABEL_BO, LABEL_FO) VALUES
                ('NDP_CLOSED', NULL, 2, NULL, NULL, 1, NULL);

INSERT INTO psa_label_langue_site (LABEL_ID, LANGUE_ID, SITE_ID, LABEL_TRANSLATE) VALUES
            ('NDP_CLOSED', 1, 1, 'Fermé');
