<?php namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150526173741 extends AbstractMigration
{

    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {

        $this->addSql("UPDATE `psa_zone_template` SET `ZONE_TEMPLATE_ID` = '1', `ZONE_TEMPLATE_LABEL` = 'NDP_PT2_ADMIN_BESOINAIDE', `TEMPLATE_PAGE_ID` = '150', `AREA_ID` = '122', `ZONE_ID` = '803', `ZONE_TEMPLATE_ORDER` = '1', `ZONE_TEMPLATE_MOBILE_ORDER` = NULL, `ZONE_TEMPLATE_TABLET_ORDER` = NULL, `ZONE_TEMPLATE_TV_ORDER` = NULL, `ZONE_CACHE_TIME` = '30' WHERE `TEMPLATE_PAGE_ID` = '150' AND `ZONE_TEMPLATE_ID` = '1';");
        $this->addSql("UPDATE `psa_zone_template` SET `ZONE_TEMPLATE_ID` = '2', `ZONE_TEMPLATE_LABEL` = 'NDP_PT2_ADMIN_LAGAMME', `TEMPLATE_PAGE_ID` = '150', `AREA_ID` = '122', `ZONE_ID` = '806', `ZONE_TEMPLATE_ORDER` = '2', `ZONE_TEMPLATE_MOBILE_ORDER` = NULL, `ZONE_TEMPLATE_TABLET_ORDER` = NULL, `ZONE_TEMPLATE_TV_ORDER` = NULL, `ZONE_CACHE_TIME` = '30' WHERE `TEMPLATE_PAGE_ID` = '150' AND `ZONE_TEMPLATE_ID` = '2';");
        $this->addSql("UPDATE `psa_zone_template` SET `ZONE_TEMPLATE_ID` = '3', `ZONE_TEMPLATE_LABEL` = 'NDP_PT2_ADMIN_NEWSLETTER', `TEMPLATE_PAGE_ID` = '150', `AREA_ID` = '122', `ZONE_ID` = '807', `ZONE_TEMPLATE_ORDER` = '4', `ZONE_TEMPLATE_MOBILE_ORDER` = NULL, `ZONE_TEMPLATE_TABLET_ORDER` = NULL, `ZONE_TEMPLATE_TV_ORDER` = NULL, `ZONE_CACHE_TIME` = '30' WHERE `TEMPLATE_PAGE_ID` = '150' AND `ZONE_TEMPLATE_ID` = '3';");
        $this->addSql("UPDATE `psa_zone_template` SET `ZONE_TEMPLATE_ID` = '4', `ZONE_TEMPLATE_LABEL` = 'NDP_PT2_ADMIN_SERVICECLIENT', `TEMPLATE_PAGE_ID` = '150', `AREA_ID` = '122', `ZONE_ID` = '810', `ZONE_TEMPLATE_ORDER` = '5', `ZONE_TEMPLATE_MOBILE_ORDER` = NULL, `ZONE_TEMPLATE_TABLET_ORDER` = NULL, `ZONE_TEMPLATE_TV_ORDER` = NULL, `ZONE_CACHE_TIME` = '30' WHERE `TEMPLATE_PAGE_ID` = '150' AND `ZONE_TEMPLATE_ID` = '4';");
        $this->addSql("UPDATE `psa_zone_template` SET `ZONE_TEMPLATE_ID` = '5', `ZONE_TEMPLATE_LABEL` = 'NDP_PT2_ADMIN_RESEAUXSOCIAUX', `TEMPLATE_PAGE_ID` = '150', `AREA_ID` = '122', `ZONE_ID` = '809', `ZONE_TEMPLATE_ORDER` = '3', `ZONE_TEMPLATE_MOBILE_ORDER` = NULL, `ZONE_TEMPLATE_TABLET_ORDER` = NULL, `ZONE_TEMPLATE_TV_ORDER` = NULL, `ZONE_CACHE_TIME` = '30' WHERE `TEMPLATE_PAGE_ID` = '150' AND `ZONE_TEMPLATE_ID` = '5';");
        $this->addSql("UPDATE `psa_zone_template` SET `ZONE_TEMPLATE_ID` = '6', `ZONE_TEMPLATE_LABEL` = 'NDP_PT2_ADMIN_CTAFOOTER', `TEMPLATE_PAGE_ID` = '150', `AREA_ID` = '122', `ZONE_ID` = '804', `ZONE_TEMPLATE_ORDER` = '6', `ZONE_TEMPLATE_MOBILE_ORDER` = NULL, `ZONE_TEMPLATE_TABLET_ORDER` = NULL, `ZONE_TEMPLATE_TV_ORDER` = NULL, `ZONE_CACHE_TIME` = '30' WHERE `TEMPLATE_PAGE_ID` = '150' AND `ZONE_TEMPLATE_ID` = '6';");
        $this->addSql("UPDATE `psa_zone_template` SET `ZONE_TEMPLATE_ID` = '7', `ZONE_TEMPLATE_LABEL` = 'NDP_PT2_ADMIN_PLANDUSITE', `TEMPLATE_PAGE_ID` = '150', `AREA_ID` = '122', `ZONE_ID` = '808', `ZONE_TEMPLATE_ORDER` = '7', `ZONE_TEMPLATE_MOBILE_ORDER` = NULL, `ZONE_TEMPLATE_TABLET_ORDER` = NULL, `ZONE_TEMPLATE_TV_ORDER` = NULL, `ZONE_CACHE_TIME` = '30' WHERE `TEMPLATE_PAGE_ID` = '150' AND `ZONE_TEMPLATE_ID` = '7';");
        $this->addSql("UPDATE `psa_zone_template` SET `ZONE_TEMPLATE_ID` = '8', `ZONE_TEMPLATE_LABEL` = 'NDP_PT2_ADMIN_ELEMENTSLEGAUX', `TEMPLATE_PAGE_ID` = '150', `AREA_ID` = '122', `ZONE_ID` = '805', `ZONE_TEMPLATE_ORDER` = '8', `ZONE_TEMPLATE_MOBILE_ORDER` = NULL, `ZONE_TEMPLATE_TABLET_ORDER` = NULL, `ZONE_TEMPLATE_TV_ORDER` = NULL, `ZONE_CACHE_TIME` = '30' WHERE `TEMPLATE_PAGE_ID` = '150' AND `ZONE_TEMPLATE_ID` = '8';");
        $this->addSql("UPDATE `psa_zone_template` SET `ZONE_TEMPLATE_ID` = '9', `ZONE_TEMPLATE_LABEL` = 'NDP_PT3_JE_VEUX', `TEMPLATE_PAGE_ID` = '150', `AREA_ID` = '121', `ZONE_ID` = '801', `ZONE_TEMPLATE_ORDER` = '2', `ZONE_TEMPLATE_MOBILE_ORDER` = NULL, `ZONE_TEMPLATE_TABLET_ORDER` = NULL, `ZONE_TEMPLATE_TV_ORDER` = NULL, `ZONE_CACHE_TIME` = '30' WHERE `TEMPLATE_PAGE_ID` = '150' AND `ZONE_TEMPLATE_ID` = '9';");
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
    }
}
