<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160113094404 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DELETE FROM `psa_page_version` WHERE TEMPLATE_PAGE_ID = 362');
        $this->addSql('DELETE FROM `psa_page` WHERE PAGE_ID = 3309');
        $this->addSql('DELETE FROM `psa_page` WHERE PAGE_ID = 3809');

        $this->addSql('UPDATE `psa_page_type` SET PAGE_TYPE_UNIQUE = 1, PAGE_TYPE_ONE_USE = 1 WHERE PAGE_TYPE_CODE = "G05"');

        $this->addSql('DELETE FROM `psa_page_zone_multi` WHERE ZONE_TEMPLATE_ID = 4452');

        $this->addSql('REPLACE INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`, `ZONE_TEMPLATE_LABEL`, `TEMPLATE_PAGE_ID`, `AREA_ID`, `ZONE_ID`, `ZONE_TEMPLATE_ORDER`, `ZONE_TEMPLATE_MOBILE_ORDER`, `ZONE_TEMPLATE_TABLET_ORDER`, `ZONE_TEMPLATE_TV_ORDER`, `ZONE_CACHE_TIME`) VALUES
            (4355, \'NDP_PT21_NAVIGATION\', 362, 10, 798, 1, 1, NULL, NULL, -2),
            (4356, \'NDP_PN7_ENTETE\', 362, 121, 791, 2, 2, NULL, NULL, -2),
            (4451, \'NDP_PT22_MY_PEUGEOT\', 362, 121, 826, 3, 3, NULL, NULL, -2),
            (4452, \'NDP_PT3_JE_VEUX\', 362, 121, 801, 4, 4, NULL, NULL, -2),
            (4353, \'NDP_PT2_FOOTER\', 362, 122, 800, 7, 7, NULL, NULL, -2),
            (4354, \'NDP_PC5_UNE_COLONNE\', 362, 148, 776, 5, 5, NULL, NULL, -2),
            (6118, \'NDP_PC40_CTA\', 362, 148, 771, 6, 6, NULL, NULL, -2)
        ');

        $this->addSql('DELETE FROM `psa_zone` WHERE ZONE_ID = 755');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('UPDATE `psa_page_type` SET PAGE_TYPE_UNIQUE = NULL, PAGE_TYPE_ONE_USE = NULL WHERE PAGE_TYPE_CODE = "G05"');

        $this->addSql('INSERT INTO `psa_zone` (`ZONE_ID`, `ZONE_TYPE_ID`, `ZONE_LABEL`, `ZONE_FREE`, `ZONE_COMMENT`, `ZONE_BO_PATH`, `ZONE_FO_PATH`, `ZONE_IFRAME`, `ZONE_AJAX`, `ZONE_PROGRAM`, `ZONE_DB_MULTI`, `ZONE_IMAGE`, `ZONE_CATEGORY_ID`, `ZONE_CONTENT`, `PLUGIN_ID`) VALUES
            (755, 1, \'NDP_PC38_PAGE_404\', 0, NULL, \'Cms_Page_Ndp_Pc38Page404\', \'Pc38PageErreur404Strategy\', 0, 0, 0, NULL, NULL, 28, 0, "")
        ');

        $this->addSql('DELETE FROM `psa_page_zone_media` WHERE ZONE_TEMPLATE_ID = 6118');
        $this->addSql('DELETE FROM `psa_zone_template` WHERE ZONE_TEMPLATE_ID = 6118');

        $this->addSql('REPLACE INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`, `ZONE_TEMPLATE_LABEL`, `TEMPLATE_PAGE_ID`, `AREA_ID`, `ZONE_ID`, `ZONE_TEMPLATE_ORDER`, `ZONE_TEMPLATE_MOBILE_ORDER`, `ZONE_TEMPLATE_TABLET_ORDER`, `ZONE_TEMPLATE_TV_ORDER`, `ZONE_CACHE_TIME`) VALUES
            (4355, \'NDP_PT21_NAVIGATION\', 362, 10, 798, 1, 1, NULL, NULL, -2),
            (4356, \'NDP_PN7_ENTETE\', 362, 121, 791, 2, 2, NULL, NULL, -2),
            (4451, \'NDP_PT22_MY_PEUGEOT\', 362, 121, 826, 3, 3, NULL, NULL, -2),
            (4452, \'NDP_PT3_JE_VEUX\', 362, 121, 801, 4, 4, NULL, NULL, -2),
            (4353, \'NDP_PT2_FOOTER\', 362, 122, 800, 5, 5, NULL, NULL, -2),
            (4354, \'NDP_PC38_PAGE_404\', 362, 148, 755, 4, 4, NULL, NULL, -2)
        ');

        $this->addSql('INSERT INTO `psa_page_zone_multi` (`PAGE_ID`, `LANGUE_ID`, `PAGE_VERSION`, `ZONE_TEMPLATE_ID`, `PAGE_ZONE_MULTI_ID`, `PAGE_ZONE_MULTI_TYPE`, `PAGE_ZONE_MULTI_TITRE`, `PAGE_ZONE_MULTI_TITRE2`, `PAGE_ZONE_MULTI_TITRE3`, `PAGE_ZONE_MULTI_TITRE4`, `MEDIA_ID`, `MEDIA_ID2`, `MEDIA_ID3`, `MEDIA_ID4`, `MEDIA_ID5`, `MEDIA_ID6`, `YOUTUBE_ID`, `PAGE_ZONE_MULTI_LABEL`, `PAGE_ZONE_MULTI_LABEL2`, `PAGE_ZONE_MULTI_LABEL3`, `PAGE_ZONE_MULTI_LABEL4`, `PAGE_ZONE_MULTI_LABEL5`, `PAGE_ZONE_MULTI_LABEL6`, `PAGE_ZONE_MULTI_LABEL7`, `PAGE_ZONE_MULTI_LABEL8`, `PAGE_ZONE_MULTI_VALUE`, `PAGE_ZONE_MULTI_VALUE2`, `PAGE_ZONE_MULTI_VALUE3`, `PAGE_ZONE_MULTI_VALUE4`, `PAGE_ZONE_MULTI_TEXT`, `PAGE_ZONE_MULTI_TEXT2`, `PAGE_ZONE_MULTI_TEXT3`, `PAGE_ZONE_MULTI_TEXT4`, `PAGE_ZONE_MULTI_URL`, `PAGE_ZONE_MULTI_URL2`, `PAGE_ZONE_MULTI_URL3`, `PAGE_ZONE_MULTI_URL4`, `PAGE_ZONE_MULTI_URL5`, `PAGE_ZONE_MULTI_URL6`, `PAGE_ZONE_MULTI_URL7`, `PAGE_ZONE_MULTI_URL8`, `PAGE_ZONE_MULTI_URL9`, `PAGE_ZONE_MULTI_URL10`, `PAGE_ZONE_MULTI_URL11`, `PAGE_ZONE_MULTI_URL12`, `PAGE_ZONE_MULTI_URL13`, `PAGE_ZONE_MULTI_URL14`, `PAGE_ZONE_MULTI_URL15`, `PAGE_ZONE_MULTI_URL16`, `PAGE_ZONE_MULTI_DATE`, `PAGE_ZONE_MULTI_DATE2`, `PAGE_ZONE_MULTI_DATE_BEGIN`, `PAGE_ZONE_MULTI_DATE_END`, `PAGE_ZONE_MULTI_ATTRIBUT`, `PAGE_ZONE_MULTI_ATTRIBUT2`, `PAGE_ZONE_MULTI_MODE`, `PAGE_ZONE_MULTI_MODE2`, `PAGE_ZONE_MULTI_MODE3`, `PAGE_ZONE_MULTI_MODE4`, `PAGE_ZONE_MULTI_OPTION`, `PAGE_ZONE_MULTI_ORDER`, `CONTENT_ID`) VALUES
            (3309, 1, 1, 4452, 1, \'NDP_COLONNE1\', \'CHOISIR UNE VOITURE\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
            (3309, 1, 1, 4452, 2, \'NDP_COLONNE2\', \'ACHETER UNE VOITURE\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
            (3309, 1, 1, 4452, 3, \'NDP_COLONNE3\', \'ENTRETIENS & SERVICES\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
            (3309, 1, 1, 4452, 4, \'NDP_COLONNE4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
            (3309, 1, 2, 4452, 1, \'NDP_COLONNE1\', \'CHOISIR UNE VOITURE\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
            (3309, 1, 2, 4452, 2, \'NDP_COLONNE2\', \'ACHETER UNE VOITURE\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
            (3309, 1, 2, 4452, 3, \'NDP_COLONNE3\', \'ENTRETIENS & SERVICES\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
            (3309, 1, 2, 4452, 4, \'NDP_COLONNE4\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
        ');

        $this->addSql('INSERT INTO `psa_page` (`PAGE_ID`, `LANGUE_ID`, `PAGE_PARENT_ID`, `SITE_ID`, `PAGE_TYPE_ID`, `PAGE_CURRENT_VERSION`, `PAGE_DRAFT_VERSION`, `PAGE_CREATION_DATE`, `PAGE_CREATION_USER`, `PAGE_STATUS`, `PAGE_ARCHIVE`, `PAGE_PATH`, `PAGE_LIBPATH`, `PAGE_ORDER`, `PAGE_GENERAL`, `PAGE_METIER`, `PAGE_DIFFUSION`, `PAGE_ID_SOURCE`) VALUES
            (3809, 1, 1, 2, NULL, 7, 7, \'2015-11-09 00:00:00\', \'#admin#\', 1, 0, \'1#3809\', \'1|Accueil#3809|PAGE 404\', 8, 0, NULL, NULL, NULL),
            (3309, 1, 3035, 2, NULL, 42, 42, \'2015-06-29 00:00:00\', \'#admin#\', 1, 0, \'1#3035#3309\', \'1|Accueil#3035|Hicham#3309|Hicham - Gabarit 404\', 37, 0, NULL, NULL, NULL)
        ');
        $this->addSql('INSERT INTO `psa_page_version` (`PAGE_ID`, `LANGUE_ID`, `PAGE_VERSION`, `STATE_ID`, `TEMPLATE_PAGE_ID`, `PAGE_TITLE_BO`, `PAGE_TITLE`, `PAGE_SUBTITLE`, `PAGE_TEXT`, `PAGE_SHORTTEXT`, `PAGE_CODE`, `PAGE_URL`, `PAGE_DATE`, `MEDIA_ID`, `PAGE_CLEAR_URL`, `PAGE_PICTO_URL`, `PAGE_TITLE_URL`, `PAGE_EXTERNAL_LINK`, `PAGE_META_TITLE`, `PAGE_META_DESC`, `PAGE_META_KEYWORD`, `PAGE_META_ROBOTS`, `PAGE_META_URL_CANONIQUE`, `PAGE_START_DATE`, `PAGE_END_DATE`, `PAGE_PUBLICATION_DATE`, `PAGE_VERSION_CREATION_DATE`, `PAGE_VERSION_CREATION_USER`, `PAGE_VERSION_UPDATE_DATE`, `PAGE_VERSION_UPDATE_USER`, `PAGE_AUTHOR`, `PAGE_LATITUDE`, `PAGE_LONGITUDE`, `PAGE_DISPLAY`, `PAGE_DISPLAY_SEARCH`, `PAGE_DISPLAY_NAV`, `PAGE_KEYWORD`, `PUB_ID`, `PAGE_PROTOCOLE_HTTPS`, `PAGE_MODE_AFFICHAGE`, `PAGE_URL_EXTERNE`, `PAGE_URL_EXTERNE_MODE_OUVERTURE`, `PAGE_TYPE_EXPAND`, `PAGE_OUVRIR_NIVEAU_3`, `PAGE_NB_ITEM_PAR_LIGNE`, `PAGE_MENTIONS_LEGALES`, `MEDIA_ID2`, `PAGE_GAMME_VEHICULE`, `PAGE_VEHICULE`, `PAGE_PERSO`, `PAGE_LANGUETTE_PRO`, `PAGE_LANGUETTE_CLIENT`, `PAGE_OUVERTURE_DIRECT`, `PAGE_DISPLAY_PLAN`) VALUES
            (3309, 1, 42, 4, 362, \'Hicham - Gabarit 404\', \'Hicham - Gabarit 404\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'/fr/hicham/hicham-gabarit-404.html\', NULL, NULL, NULL, \'Hicham - Gabarit 404\', NULL, NULL, 2, NULL, NULL, NULL, \'2015-06-29\', \'2015-06-29 00:00:00\', \'admin\', NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
            (3809, 1, 7, 4, 362, \'PAGE 404\', \'PAGE 404\', NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'/fr/page-404.html\', NULL, NULL, NULL, \'PAGE 404\', NULL, NULL, 2, NULL, NULL, NULL, \'2015-11-09\', \'2015-11-09 00:00:00\', \'admin\', NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
        ');
    }
}
