<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150717120900 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE psa_sites_et_webservices_psa (SITE_DOMAIN_NAME VARCHAR(255) NOT NULL, ZONE_VP INT NOT NULL, ZONE_VP_POPIN INT DEFAULT NULL, ZONE_VP_POPIN_CONFIRM INT DEFAULT NULL, ZONE_SHOWROOM INT NOT NULL, ZONE_MY_PEUGEOT INT NOT NULL, ZONE_WEBSTORE INT NOT NULL, ZONE_WEBSTORE_POPIN INT DEFAULT NULL, ZONE_WEBSTORE_POPIN_CONFIRM INT DEFAULT NULL, ZONE_PARCOURS_WEBSTORE INT DEFAULT NULL, ZONE_URL_WEB_VP VARCHAR(255) DEFAULT NULL, ZONE_URL_WEB_FICHE_ACCESSOIRES VARCHAR(255) DEFAULT NULL, ZONE_URL_MOB_FICHE_ACCESSOIRES VARCHAR(255) DEFAULT NULL, ZONE_URL_WEB_ACCUEIL VARCHAR(255) DEFAULT NULL, ZONE_URL_WEB_CONNEXION VARCHAR(255) DEFAULT NULL, ZONE_URL_MOB_ACCUEIL VARCHAR(255) DEFAULT NULL, ZONE_URL_MOB_CONNEXION VARCHAR(255) DEFAULT NULL, ZONE_URL_WEB_MOB_WEBSTORE VARCHAR(255) DEFAULT NULL, ZONE_URL_WEB_MOB_WEBSTORE_PRODUITS VARCHAR(255) DEFAULT NULL, ZONE_URL_PEUGEOT_SERVICE VARCHAR(255) DEFAULT NULL, ZONE_URL_PEUGEOT_ENVIRONNEMENT VARCHAR(255) DEFAULT NULL, ZONE_URL_PEUGEOT_PRO VARCHAR(255) DEFAULT NULL, ZONE_URL_PEUGEOT_WEBSTORE_PRO VARCHAR(255) DEFAULT NULL, ZONE_URL_PRODUIT_DERIVES VARCHAR(255) DEFAULT NULL, ZONE_URL_PEUGEOT_SCOOTER VARCHAR(255) DEFAULT NULL, ZONE_URL_PEUGEOT_CYCLES VARCHAR(255) DEFAULT NULL, ZONE_URL_MU_BY_PEUGEOT VARCHAR(255) DEFAULT NULL, SITE_ID INT NOT NULL, INDEX IDX_A97E8AA3F1B5AEBC (SITE_ID), PRIMARY KEY(SITE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE psa_sites_et_webservices_psa ADD CONSTRAINT FK_A97E8AA3F1B5AEBC FOREIGN KEY (SITE_ID) REFERENCES psa_site (SITE_ID)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE psa_sites_et_webservices_psa');
    }
}
