<?php namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150603142704 extends AbstractMigration
{

    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('INSERT INTO psa_label (LABEL_ID, LABEL_INFO, LABEL_BACK, LABEL_LENGTH, LABEL_CASE, LABEL_BO, LABEL_FO) VALUES
            ("NDP_NATIONAL_PARAMETERS", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_NUMBER", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_NB_DELIMITER_MILLION", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_NB_DELIMITER_THOUSAND", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_NB_DELIMITER_DECIMAL", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_DATE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_FORMAT_DATE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_FORMAT_CLOCK", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_TIME_DIFFERENCE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_CAR_PRICE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_VEHICULE_PRICE_DISPLAY", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_CASH_PRICE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_VEHICULE_PRICE_VP_TYPE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_HT", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_TTC", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_BEFORE_PRICE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_AFTER_PRICE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_VEHICULE_PRICE_LEGAL_SYMBOL", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_VEHICULE_PRICE_LEGAL_DISPLAY", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_MONTHLY_PRICE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_MONTHLY", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_CASH", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_VEHICULE_PRICE_MONTHLY_DISPLAY", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_MSG_WS_SFG_DISABLED", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_VEHICULE_PRICE_TYPE_PAYMENT_DEFAULT", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_OTHER_PRICE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_OTHER_PRICE_TYPE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_PRICE_FROM_POSITION", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_CURRENCY", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_CURRENCY_CODE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_CURRENCY_SYMBOL", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_CURRENCY_POSITION", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_CURRENCY_USE_LOCAL", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_DISTANCE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_DISTANCE_UNIT", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_NB_DECIMAL", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_DIMENSION", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_KILOMETER", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_MILE", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_METER", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_CENTIMETER", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_MILLIMETER", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_FEET", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_INCH", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_DIMENSION_UNIT", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_DIMENSION_MULTIPLIER", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_VOLUME", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_LM3", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_GLCL", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_ML", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_BL", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_VOLUME_UNIT", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_VOLUME_MULTIPLIER", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_PAYLOAD", NULL, 2, NULL, NULL, 1, NULL),
            ("NDP_PAYLOAD_MULTIPLIER", NULL, 2, NULL, NULL, 1, NULL)
         ');
        $this->addSql('INSERT INTO psa_label_langue_site (LABEL_ID, LANGUE_ID, SITE_ID, LABEL_TRANSLATE) VALUES
            ("NDP_NATIONAL_PARAMETERS", 1, 1, "Paramètre nationaux"),
            ("NDP_NUMBER", 1, 1, "Nombre"),
            ("NDP_NB_DELIMITER_MILLION", 1, 1, "Séparateur des millions"),
            ("NDP_NB_DELIMITER_THOUSAND", 1, 1, "Séparateur des milliers"),
            ("NDP_NB_DELIMITER_DECIMAL", 1, 1, "Séparateur décimal"),
            ("NDP_DATE", 1, 1, "Date"),
            ("NDP_FORMAT_DATE", 1, 1, "Format des dates"),
            ("NDP_FORMAT_CLOCK", 1, 1, "Format des heures"),
            ("NDP_TIME_DIFFERENCE", 1, 1, "Décalage horaire à appliquer"),
            ("NDP_CAR_PRICE", 1, 1, "Prix des véhicules"),
            ("NDP_VEHICULE_PRICE_DISPLAY", 1, 1, "Affichage des prix des véhicules"),
            ("NDP_CASH_PRICE", 1, 1, "Prix comptant"),
            ("NDP_VEHICULE_PRICE_VP_TYPE", 1, 1, "Type de prix de la gamme VP"),
            ("NDP_HT", 1, 1, "HT"),
            ("NDP_TTC", 1, 1, "TTC"),
            ("NDP_BEFORE_PRICE", 1, 1, "Avant le prix"),
            ("NDP_AFTER_PRICE", 1, 1, "Après le prix"),
            ("NDP_NATIONAL_PARAMETERS", 1, 2, "Paramètre nationaux"),
            ("NDP_NUMBER", 1, 2, "Nombre"),
            ("NDP_NB_DELIMITER_MILLION", 1, 2, "Séparateur des millions"),
            ("NDP_NB_DELIMITER_THOUSAND", 1, 2, "Séparateur des milliers"),
            ("NDP_NB_DELIMITER_DECIMAL", 1, 2, "Séparateur décimal"),
            ("NDP_DATE", 1, 2, "Date"),
            ("NDP_FORMAT_DATE", 1, 2, "Format des dates"),
            ("NDP_FORMAT_CLOCK", 1, 2, "Format des heures"),
            ("NDP_TIME_DIFFERENCE", 1, 2, "Décalage horaire à appliquer"),
            ("NDP_CAR_PRICE", 1, 2, "Prix des véhicules"),
            ("NDP_VEHICULE_PRICE_DISPLAY", 1, 2, "Affichage des prix des véhicules"),
            ("NDP_CASH_PRICE", 1, 2, "Prix comptant"),
            ("NDP_VEHICULE_PRICE_VP_TYPE", 1, 2, "Type de prix de la gamme VP"),
            ("NDP_HT", 1, 2, "HT"),
            ("NDP_TTC", 1, 2, "TTC"),
            ("NDP_BEFORE_PRICE", 1, 2, "Avant le prix"),
            ("NDP_AFTER_PRICE", 1, 2, "Après le prix"),
            ("NDP_VEHICULE_PRICE_LEGAL_SYMBOL", 1, 1, "Symbole"),
            ("NDP_VEHICULE_PRICE_LEGAL_DISPLAY", 1, 1, "Activer les mentions légales"),
            ("NDP_MONTHLY_PRICE", 1, 1, "Prix mensualisés"),
            ("NDP_MONTHLY", 1, 1, "Mensualisé"),
            ("NDP_CASH", 1, 1, "Comptant"),
            ("NDP_VEHICULE_PRICE_MONTHLY_DISPLAY", 1, 1, "Affichage des prix mensualisés"),
            ("NDP_MSG_WS_SFG_DISABLED", 1, 1, "Il est nécessaire d’activer le Webservice Financement BPF dans Services afin d’afficher les prix mensualisés"),
            ("NDP_VEHICULE_PRICE_TYPE_PAYMENT_DEFAULT", 1, 1, "Mode d’affichage du prix par défaut"),
            ("NDP_OTHER_PRICE", 1, 1, "Autres prix (accessoires, services/forfaits, services connectés)"),
            ("NDP_OTHER_PRICE_TYPE", 1, 1, "Type de prix"),
            ("NDP_PRICE_FROM_POSITION", 1, 1, "Position du libellé “A partir de”"),
            ("NDP_CURRENCY", 1, 1, "Devise"),
            ("NDP_CURRENCY_CODE", 1, 1, "Code de la devise"),
            ("NDP_CURRENCY_SYMBOL", 1, 1, "Symbole de la devise"),
            ("NDP_CURRENCY_POSITION", 1, 1, "Position de la devise"),
            ("NDP_CURRENCY_USE_LOCAL", 1, 1, "Monnaie locale"),
            ("NDP_DISTANCE", 1, 1, "Distance"),
            ("NDP_DISTANCE_UNIT", 1, 1, "Unité de distance"),
            ("NDP_NB_DECIMAL", 1, 1, "Nombre de décimales"),
            ("NDP_DIMENSION", 1, 1, "Dimensions"),
            ("NDP_KILOMETER", 1, 1, "Kilomètre"),
            ("NDP_MILE", 1, 1, "Mile"),
            ("NDP_METER", 1, 1, "Mètre"),
            ("NDP_CENTIMETER", 1, 1, "Centimètre"),
            ("NDP_MILLIMETER", 1, 1, "Millimètre"),
            ("NDP_FEET", 1, 1, "Feet"),
            ("NDP_INCH", 1, 1, "Inch"),
            ("NDP_DIMENSION_UNIT", 1, 1, "Unité de longueur / largeur / hauteur"),
            ("NDP_DIMENSION_MULTIPLIER", 1, 1, "Multiplicateur à appliquer si la longueur provient du SI."),
            ("NDP_VOLUME", 1, 1, "Volume"),
            ("NDP_LM3", 1, 1, "litre / m3"),
            ("NDP_GLCL", 1, 1, "gl cl"),
            ("NDP_ML", 1, 1, "ml"),
            ("NDP_BL", 1, 1, "bl"),
            ("NDP_VOLUME_UNIT", 1, 1, "Unité de volume"),
            ("NDP_VOLUME_MULTIPLIER", 1, 1, "Multiplicateur à appliquer si le volume provient du SI."),
            ("NDP_PAYLOAD", 1, 1, "Charge utile"),
            ("NDP_PAYLOAD_MULTIPLIER", 1, 1, "Multiplicateur à appliquer si la charge utile provient du SI."),
            ("NDP_VEHICULE_PRICE_LEGAL_SYMBOL", 1, 2, "Symbole"),
            ("NDP_VEHICULE_PRICE_LEGAL_DISPLAY", 1, 2, "Activer les mentions légales"),
            ("NDP_MONTHLY_PRICE", 1, 2, "Prix mensualisés"),
            ("NDP_MONTHLY", 1, 2, "Mensualisé"),
            ("NDP_CASH", 1, 2, "Comptant"),
            ("NDP_VEHICULE_PRICE_MONTHLY_DISPLAY", 1, 2, "Affichage des prix mensualisés"),
            ("NDP_MSG_WS_SFG_DISABLED", 1, 2, "Il est nécessaire d’activer le Webservice Financement BPF dans Services afin d’afficher les prix mensualisés"),
            ("NDP_VEHICULE_PRICE_TYPE_PAYMENT_DEFAULT", 1, 2, "Mode d’affichage du prix par défaut"),
            ("NDP_OTHER_PRICE", 1, 2, "Autres prix (accessoires, services/forfaits, services connectés)"),
            ("NDP_OTHER_PRICE_TYPE", 1, 2, "Type de prix"),
            ("NDP_PRICE_FROM_POSITION", 1, 2, "Position du libellé “A partir de”"),
            ("NDP_CURRENCY", 1, 2, "Devise"),
            ("NDP_CURRENCY_CODE", 1, 2, "Code de la devise"),
            ("NDP_CURRENCY_SYMBOL", 1, 2, "Symbole de la devise"),
            ("NDP_CURRENCY_POSITION", 1, 2, "Position de la devise"),
            ("NDP_CURRENCY_USE_LOCAL", 1, 2, "Monnaie locale"),
            ("NDP_DISTANCE", 1, 2, "Distance"),
            ("NDP_DISTANCE_UNIT", 1, 2, "Unité de distance"),
            ("NDP_NB_DECIMAL", 1, 2, "Nombre de décimales"),
            ("NDP_DIMENSION", 1, 2, "Dimensions"),
            ("NDP_KILOMETER", 1, 2, "Kilomètre"),
            ("NDP_MILE", 1, 2, "Mile"),
            ("NDP_METER", 1, 2, "Mètre"),
            ("NDP_CENTIMETER", 1, 2, "Centimètre"),
            ("NDP_MILLIMETER", 1, 2, "Millimètre"),
            ("NDP_FEET", 1, 2, "Feet"),
            ("NDP_INCH", 1, 2, "Inch"),
            ("NDP_DIMENSION_UNIT", 1, 2, "Unité de longueur / largeur / hauteur"),
            ("NDP_DIMENSION_MULTIPLIER", 1, 2, "Multiplicateur à appliquer si la longueur provient du SI."),
            ("NDP_VOLUME", 1, 2, "Volume"),
            ("NDP_LM3", 1, 2, "litre / m3"),
            ("NDP_GLCL", 1, 2, "gl cl"),
            ("NDP_ML", 1, 2, "ml"),
            ("NDP_BL", 1, 2, "bl"),
            ("NDP_VOLUME_UNIT", 1, 2, "Unité de volume"),
            ("NDP_VOLUME_MULTIPLIER", 1, 2, "Multiplicateur à appliquer si le volume provient du SI."),
            ("NDP_PAYLOAD", 1, 2, "Charge utile"),
            ("NDP_PAYLOAD_MULTIPLIER", 1, 2, "Multiplicateur à appliquer si la charge utile provient du SI.")'
        );
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $tables = array('psa_label', 'psa_label_langue_site');
        foreach ($tables as $table) {
            $this->addSql(
                'DELETE FROM `'.$table.'`  WHERE  `LABEL_ID` IN
                 (
                    "NDP_NATIONAL_PARAMETERS",
                    "NDP_NUMBER",
                    "NDP_NB_DELIMITER_MILLION",
                    "NDP_NB_DELIMITER_THOUSAND",
                    "NDP_NB_DELIMITER_DECIMAL",
                    "NDP_DATE",
                    "NDP_FORMAT_DATE",
                    "NDP_FORMAT_CLOCK",
                    "NDP_TIME_DIFFERENCE",
                    "NDP_CAR_PRICE",
                    "NDP_VEHICULE_PRICE_DISPLAY",
                    "NDP_CASH_PRICE",
                    "NDP_VEHICULE_PRICE_VP_TYPE",
                    "NDP_HT",
                    "NDP_TTC",
                    "NDP_BEFORE_PRICE",
                    "NDP_AFTER_PRICE",
                    "NDP_VEHICULE_PRICE_LEGAL_SYMBOL",
                    "NDP_VEHICULE_PRICE_LEGAL_DISPLAY",
                    "NDP_MONTHLY_PRICE",
                    "NDP_MONTHLY",
                    "NDP_CASH",
                    "NDP_VEHICULE_PRICE_MONTHLY_DISPLAY",
                    "NDP_MSG_WS_SFG_DISABLED",
                    "NDP_VEHICULE_PRICE_TYPE_PAYMENT_DEFAULT",
                    "NDP_OTHER_PRICE",
                    "NDP_OTHER_PRICE_TYPE",
                    "NDP_PRICE_FROM_POSITION",
                    "NDP_CURRENCY",
                    "NDP_CURRENCY_CODE",
                    "NDP_CURRENCY_SYMBOL",
                    "NDP_CURRENCY_POSITION",
                    "NDP_CURRENCY_USE_LOCAL",
                    "NDP_DISTANCE",
                    "NDP_DISTANCE_UNIT",
                    "NDP_NB_DECIMAL",
                    "NDP_DIMENSION",
                    "NDP_KILOMETER",
                    "NDP_MILE",
                    "NDP_METER",
                    "NDP_CENTIMETER",
                    "NDP_MILLIMETER",
                    "NDP_FEET",
                    "NDP_INCH",
                    "NDP_DIMENSION_UNIT",
                    "NDP_DIMENSION_MULTIPLIER",
                    "NDP_VOLUME",
                    "NDP_LM3",
                    "NDP_GLCL",
                    "NDP_ML",
                    "NDP_BL",
                    "NDP_VOLUME_UNIT",
                    "NDP_VOLUME_MULTIPLIER",
                    "NDP_PAYLOAD",
                    "NDP_PAYLOAD_MULTIPLIER"
                )');
        }
    }
}
