<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150618171843 extends AbstractMigration
{

    public function preUp(Schema $schema)
    {
        $this->defaultFormat();

    }
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('1/3 ou Actualité Mobile', 1, 640, 213,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('1/3 ou Entête petit visuel ou Actualité visuel unique HD', 1, 2560, 854,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('1/3 ou Entête petit visuel ou Actualité visuel unique Standard', 1, 1280, 427,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('1/3 ou Entête petit visuel ou Actualité visuel unique Ultra HD', 1, 3328, 1110,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 HD', 1, 2560, 1440,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 ou CTA ou Offre + ou Présentation confishow Mobile', 1, 640, 360,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 prehome importateurs HD', 1, 1150, 646,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 prehome importateurs Standard', 1, 575, 323,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 prehome importateurs Ultra HD', 1, 1495, 840,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 Standard', 1, 1280, 720,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 Ultra HD', 1, 3328, 1872,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 autopromo ou slider pop-in HD', 1, 1420, 1064,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 autopromo ou slider pop-in Standard', 1, 630, 472,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 autopromo ou slider pop-in Ultra HD', 1, 1638, 1227,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 ou Slideshow homepage ou visuel pop-in ou visuel moteur Mobile', 1, 640, 480,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 posts ou visuel moteur grand HD', 1, 850, 638,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 posts ou visuel moteur grand Ultra HD', 1, 1105, 830,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 posts ou visuel moteur Standard', 1, 425, 319,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Actualité ou Offre + visuel majeur HD', 1, 1708, 478,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Actualité ou Offre + visuel majeur Standard', 1, 854, 239,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Actualité ou Offre + visuel majeur Ultra HD', 1, 2218, 621,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badge Reevoo ou logo Blue Hdi HD', 1, 324, 64,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badge Reevoo ou logo Blue Hdi Standard', 1, 162, 32,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badge Reevoo ou logo Blue Hdi Ultra HD', 1, 420, 83,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badges applications HD ou mobile', 1, 270, 80,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badges applications Standard', 1, 135, 40,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badges applications Ultra HD', 1, 351, 104,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Finition visuel pop-in accessoire/motorisation HD', 1, 2020, 1136,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Finition visuel pop-in accessoire/motorisation Standard', 1, 1010, 568,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Finition visuel pop-in accessoire/motorisation Ultra HD', 1, 2626, 1479,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 grand visuel HD', 1, 1368, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 grand visuel Standard', 1, 684, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 grand visuel Ultra HD', 1, 1778, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 petit visuel Standard', 1, 600, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 petit visuel, 1 article 3 visuels ou 3 colonnes HD', 1, 1200, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 petit visuel, 3 visuels ou 3 colonnes Ultra HD', 1, 1560, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 3 visuels Mobile', 1, 586, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 3 visuels Standard', 1, 345, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 colonne HD', 1, 2080, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 colonne Standard', 1, 1040, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 colonne Ultra HD', 1, 2704, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 ou 2 colonnes Mobile', 1, 640, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes HD', 1, 1038, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel majeur HD', 1, 1545, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel majeur Standard', 1, 773, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel majeur Ultra HD', 1, 2009, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel mineur HD', 1, 483, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel mineur Mobile', 1, 420, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel mineur Standard', 1, 241, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel mineur Ultra HD', 1, 627, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes Standard', 1, 519, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes Ultra HD', 1, 1349, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 3 colonnes Mobile', 1, 572, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 3 colonnes Standard', 1, 345, 0,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format IAB billboard Mobile', 1, 640, 165,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format IAB billboard Standard', 1, 970, 250,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format IAB mega bannière Standard', 1, 728, 90,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format IAB pavé Standard et Mobile', 1, 300, 250,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette illustration Standard', 1, 250, 140,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette illustration HD', 1, 500, 281,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette illustration Ultra HD', 1, 650, 365,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette produits APV Mobile', 1, 290, 163,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette produits APV HD', 1, 660, 370,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette produits APV Standard', 1, 330, 185,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette produits APV Ultra HD', 1, 858, 481,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format CTA Standard', 1, 210, 118,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette services connectés Mobile', 1, 318, 318,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Garnissage HD', 1, 944, 944,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Garnissage Standard', 1, 472, 472,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Garnissage Ultra HD', 1, 1227, 1227,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Icone application HD', 1, 260, 260,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Icone application Mobile', 1, 200, 200,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Icone application Standard', 1, 130, 130,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Icone application Ultra HD', 1, 338, 338,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Offre + (x3) ou Engagement ou Actualité ou Offre + visuel mineur ou Format vignette services connectés HD', 1, 850, 478,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Offre + (x3) ou Engagement ou Actualité ou Offre + visuel mineur ou Format vignette services connectés Standard', 1, 425, 239,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Offre + (x3) ou Engagement ou Actualité ou Offre + visuel mineur ou Format vignette services connectés Ultra HD', 1, 1105, 620,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto gamme car selector HD', 1, 315, 150,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto gamme car selector Mobile', 1, 262, 125,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto gamme car selector Standard', 1, 157, 75,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto gamme car selector Ultra HD', 1, 409, 195,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto réseaux sociaux services ou tools HD', 1, 190, 190,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto réseaux sociaux, services ou tools Ultra HD', 1, 247, 247,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto réseaux sociaux, services, verbatim (mobile) ou tools Standard et Mobile', 1, 95, 95,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto USP full HD', 1, 130, 130,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto USP full Standard', 1, 65, 65,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto USP full Ultra HD', 1, 169, 169,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Présentation confishow HD', 1, 2560, 890,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Présentation confishow Standard', 1, 1280, 445,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Présentation confishow Ultra HD', 1, 3328, 1157,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Slideshow homepage ou Entête grand visuel HD', 1, 2560, 1292,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Slideshow homepage ou Entête grand visuel Standard', 1, 1280, 646,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Slideshow homepage ou Entête grand visuel Ultra HD', 1, 3328, 1680,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand carré HD', 1, 1014, 1014,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand carré Mobile', 1, 600, 600,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand carré Standard', 1, 507, 507,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand carré Ultra HD', 1, 1318, 1318,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand rectangle HD', 1, 2076, 588,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand rectangle Standard', 1, 1038, 294,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand rectangle Ultra HD', 1, 2699, 764,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit carré grand picto HD', 1, 480, 480,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit carré grand picto Ultra HD', 1, 624, 624,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit carré Mobile', 1, 290, 290,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit carré ou grand picto Standard', 1, 240, 240,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit rectangle HD', 1, 1014, 482,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit rectangle Mobile', 1, 300, 143,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit rectangle Standard', 1, 507, 241,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit rectangle Ultra HD', 1, 1318, 627,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Verbatim HD', 1, 380, 380,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Verbatim Standard', 1, 193, 193,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Verbatim Ultra HD', 1, 494, 494,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC83) HD', 1, 1110, 740,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC83) Standard', 1, 555, 370,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC83) Ultra HD', 1, 1443, 962,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC89) x3 HD', 1, 850, 566,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC89) x3 Standard', 1, 425, 283,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC89) x3 Ultra HD', 1, 1117, 744,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette jantes ou décors x4 HD', 1, 400, 300,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette jantes ou décors x4 Standard', 1, 200, 150,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette jantes ou décors x4 Ultra HD', 1, 520, 390,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement Mobile', 1, 142, 80,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement moyenne HD', 1, 400, 225,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement moyenne Standard', 1, 200, 112,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement moyenne Ultra HD', 1, 520, 292,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement petite HD', 1, 180, 101,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement petite Standard', 1, 90, 50,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement petite Ultra HD', 1, 234, 131,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel moteur petit 4/3 Mobile', 1, 210, 158,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel pack (pop-in) Standard ou Mobile', 1, 421, 316,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule Reprise', 1, 690, 345,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand ou Pop-in Offre + Standard', 1, 1030, 515,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand ou Pop-in Offre + HD', 1, 2060, 1030,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand ou Pop-in Offre + Ultra HD', 1, 2678, 1339,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand ou Pop-in Offre + mobile', 1, 640, 320,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule petit Mobile', 1, 210, 97,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule petit HD', 1, 700, 324,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule petit Standard', 1, 350, 162,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule petit Ultra HD', 1, 910, 421,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand Mobile', 1, 600, 278,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand Standard', 1, 1030, 476,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand HD', 1, 2060, 952,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand Ultra HD', 1, 2678, 1238,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette dimension Standard', 1, 200, 100,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette dimension HD', 1, 400, 200,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette dimension Ultra HD', 1, 520, 260,'',0)");

    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->defaultFormat();

    }


    private function defaultFormat(){
        $this->addSql('TRUNCATE psa_content_zone_media');
        $this->addSql('TRUNCATE psa_page_multi_zone_media');
        $this->addSql('TRUNCATE psa_page_zone_media');
        $this->addSql('TRUNCATE psa_media_format_intercept');
        $this->addSql('DELETE FROM psa_media_format');
        $this->addSql('ALTER TABLE psa_media_format AUTO_INCREMENT = 1');
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUE ('Vignette', 1, 45, 60, '0', 0)");
    }
}
