<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150626145301 extends AbstractMigration
{
    public function preUp(Schema $schema)
    {
        $this->defaultFormat();

    }
    
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('1/3 ou Actualité Mobile', 1, 213, 640,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('1/3 ou Entête petit visuel ou Actualité visuel unique HD', 1, 854, 2560,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('1/3 ou Entête petit visuel ou Actualité visuel unique Standard', 1, 427, 1280,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('1/3 ou Entête petit visuel ou Actualité visuel unique Ultra HD', 1, 1110, 3328,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 HD', 1, 1440, 2560,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 ou CTA ou Offre + ou Présentation confishow Mobile', 1, 360, 640,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 prehome importateurs HD', 1, 646, 1150,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 prehome importateurs Standard', 1, 323, 575,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 prehome importateurs Ultra HD', 1, 840, 1495,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 Standard', 1, 720, 1280,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('16/9 Ultra HD', 1, 1872, 3328,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 autopromo ou slider pop-in HD', 1, 1064, 1420,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 autopromo ou slider pop-in Standard', 1, 472, 630,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 autopromo ou slider pop-in Ultra HD', 1, 1227, 1638,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 ou Slideshow homepage ou visuel pop-in ou visuel moteur Mobile', 1, 480, 640,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 posts ou visuel moteur grand HD', 1, 638, 850,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 posts ou visuel moteur grand Ultra HD', 1, 830, 1105,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('4/3 posts ou visuel moteur Standard', 1, 319, 425,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Actualité ou Offre + visuel majeur HD', 1, 478, 1708,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Actualité ou Offre + visuel majeur Standard', 1, 239, 854,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Actualité ou Offre + visuel majeur Ultra HD', 1, 621, 2218,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badge Reevoo ou logo Blue Hdi HD', 1, 64, 324,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badge Reevoo ou logo Blue Hdi Standard', 1, 32, 162,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badge Reevoo ou logo Blue Hdi Ultra HD', 1, 83, 420,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badges applications HD ou mobile', 1, 80, 270,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badges applications Standard', 1, 40, 135,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Badges applications Ultra HD', 1, 104, 351,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Finition visuel pop-in accessoire/motorisation HD', 1, 1136, 2020,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Finition visuel pop-in accessoire/motorisation Standard', 1, 568, 1010,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Finition visuel pop-in accessoire/motorisation Ultra HD', 1, 1479, 2626,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 grand visuel HD', 1, 0, 1368,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 grand visuel Standard', 1, 0, 684,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 grand visuel Ultra HD', 1, 0, 1778,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 petit visuel Standard', 1, 0, 600,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 petit visuel, 1 article 3 visuels ou 3 colonnes HD', 1, 0, 1200,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 1 petit visuel, 3 visuels ou 3 colonnes Ultra HD', 1, 0, 1560,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 3 visuels Mobile', 1, 0, 586,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 article 3 visuels Standard', 1, 0, 345,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 colonne HD', 1, 0, 2080,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 colonne Standard', 1, 0, 1040,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 colonne Ultra HD', 1, 0, 2704,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 1 ou 2 colonnes Mobile', 1, 0, 640,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes HD', 1, 0, 1038,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel majeur HD', 1, 0, 1545,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel majeur Standard', 1, 0, 773,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel majeur Ultra HD', 1, 0, 2009,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel mineur HD', 1, 0, 483,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel mineur Mobile', 1, 0, 420,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel mineur Standard', 1, 0, 241,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes mixtes visuel mineur Ultra HD', 1, 0, 627,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes Standard', 1, 0, 519,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 2 colonnes Ultra HD', 1, 0, 1349,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 3 colonnes Mobile', 1, 0, 572,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format 3 colonnes Standard', 1, 0, 345,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format IAB billboard Mobile', 1, 165, 640,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format IAB billboard Standard', 1, 250, 970,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format IAB mega bannière Standard', 1, 90, 728,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format IAB pavé Standard et Mobile', 1, 250, 300,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette illustration Standard', 1, 140, 250,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette illustration HD', 1, 281, 500,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette illustration Ultra HD', 1, 365, 650,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette produits APV Mobile', 1, 163, 290,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette produits APV HD', 1, 370, 660,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette produits APV Standard', 1, 185, 330,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette produits APV Ultra HD', 1, 481, 858,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format CTA Standard', 1, 118, 210,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Format vignette services connectés Mobile', 1, 318, 318,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Garnissage HD', 1, 944, 944,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Garnissage Standard', 1, 472, 472,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Garnissage Ultra HD', 1, 1227, 1227,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Icone application HD', 1, 260, 260,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Icone application Mobile', 1, 200, 200,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Icone application Standard', 1, 130, 130,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Icone application Ultra HD', 1, 338, 338,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Offre + (x3) ou Engagement ou Actualité ou Offre + visuel mineur ou Format vignette services connectés HD', 1, 478, 850,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Offre + (x3) ou Engagement ou Actualité ou Offre + visuel mineur ou Format vignette services connectés Standard', 1, 239, 425,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Offre + (x3) ou Engagement ou Actualité ou Offre + visuel mineur ou Format vignette services connectés Ultra HD', 1, 620, 1105,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto gamme car selector HD', 1, 150, 315,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto gamme car selector Mobile', 1, 125, 262,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto gamme car selector Standard', 1, 75, 157,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto gamme car selector Ultra HD', 1, 195, 409,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto réseaux sociaux services ou tools HD', 1, 190, 190,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto réseaux sociaux, services ou tools Ultra HD', 1, 247, 247,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto réseaux sociaux, services, verbatim (mobile) ou tools Standard et Mobile', 1, 95, 95,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto USP full HD', 1, 130, 130,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto USP full Standard', 1, 65, 65,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Picto USP full Ultra HD', 1, 169, 169,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Présentation confishow HD', 1, 890, 2560,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Présentation confishow Standard', 1, 445, 1280,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Présentation confishow Ultra HD', 1, 1157, 3328,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Slideshow homepage ou Entête grand visuel HD', 1, 1292, 2560,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Slideshow homepage ou Entête grand visuel Standard', 1, 646, 1280,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Slideshow homepage ou Entête grand visuel Ultra HD', 1, 1680, 3328,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand carré HD', 1, 1014, 1014,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand carré Mobile', 1, 600, 600,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand carré Standard', 1, 507, 507,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand carré Ultra HD', 1, 1318, 1318,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand rectangle HD', 1, 588, 2076,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand rectangle Standard', 1, 294, 1038,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque grand rectangle Ultra HD', 1, 764, 2699,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit carré grand picto HD', 1, 480, 480,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit carré grand picto Ultra HD', 1, 624, 624,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit carré Mobile', 1, 290, 290,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit carré ou grand picto Standard', 1, 240, 240,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit rectangle HD', 1, 482, 1014,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit rectangle Mobile', 1, 143, 300,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit rectangle Standard', 1, 241, 507,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('USP mosaïque petit rectangle Ultra HD', 1, 627, 1318,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Verbatim HD', 1, 380, 380,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Verbatim Standard', 1, 193, 193,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Verbatim Ultra HD', 1, 494, 494,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC83) HD', 1, 740, 1110,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC83) Standard', 1, 370, 555,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC83) Ultra HD', 1, 962, 1443,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC89) x3 HD', 1, 566, 850,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC89) x3 Standard', 1, 283, 425,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette accessoire (PC89) x3 Ultra HD', 1, 744, 1117,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette jantes ou décors x4 HD', 1, 300, 400,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette jantes ou décors x4 Standard', 1, 150, 200,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette jantes ou décors x4 Ultra HD', 1, 390, 520,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement Mobile', 1, 80, 142,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement moyenne HD', 1, 225, 400,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement moyenne Standard', 1, 112, 200,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement moyenne Ultra HD', 1, 292, 520,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement petite HD', 1, 101, 180,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement petite Standard', 1, 50, 90,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette teinte/équipement petite Ultra HD', 1, 131, 234,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel moteur petit 4/3 Mobile', 1, 158, 210,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel pack (pop-in) Standard ou Mobile', 1, 316, 421,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule Reprise', 1, 345, 690,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand ou Pop-in Offre + Standard', 1, 515, 1030,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand ou Pop-in Offre + HD', 1, 1030, 2060,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand ou Pop-in Offre + Ultra HD', 1, 1339, 2678,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand ou Pop-in Offre + mobile', 1, 320, 640,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule petit Mobile', 1, 97, 210,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule petit HD', 1, 324, 700,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule petit Standard', 1, 162, 350,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule petit Ultra HD', 1, 421, 910,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand Mobile', 1, 278, 600,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand Standard', 1, 476, 1030,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand HD', 1, 952, 2060,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Visuel véhicule grand Ultra HD', 1, 1238, 2678,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette dimension Standard', 1, 100, 200,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette dimension HD', 1, 200, 400,'',0)");
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUES ('Vignette dimension Ultra HD', 1, 260, 520,'',0)");
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->defaultFormat();

    }


    private function defaultFormat(){
        $this->addSql('TRUNCATE psa_content_zone_media');
        $this->addSql('TRUNCATE psa_page_multi_zone_media');
        $this->addSql('TRUNCATE psa_page_zone_media');
        $this->addSql('TRUNCATE psa_media_format_intercept');
        $this->addSql('DELETE FROM psa_media_format');
        $this->addSql('ALTER TABLE psa_media_format AUTO_INCREMENT = 1');
        $this->addSql("INSERT INTO `psa_media_format` (`MEDIA_FORMAT_LABEL`, `MEDIA_FORMAT_RATIO`, `MEDIA_FORMAT_HEIGHT`, `MEDIA_FORMAT_WIDTH`, `MEDIA_FORMAT_COLORS`, `MEDIA_FORMAT_COMPLETE`) VALUE ('Vignette', 1, 45, 60, '0', 0)");
    }
}
