<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150424141009 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37B4EDB1E5622E2C229381310BA07F8665F342437');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37B4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37E1DF977A');
        $this->addSql('DROP INDEX IDX_F83E37B4EDB1E5622E2C229381310BA07F8665F342437 ON psa_page_multi_zone_multi_cta_cta');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD PAGE_ZONE_MULTI_ID INT NOT NULL, ADD PAGE_ZONE_MULTI_TYPE VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DFAC FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_multi_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_F83E37B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DFA ON psa_page_multi_zone_multi_cta_cta (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE)');

        $this->addSql('ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CB4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CB4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CE1DF977A');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CB4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6 FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta DROP PRIMARY KEY, ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE, PAGE_ZONE_CTA_TYPE)');

        $this->addSql('ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385B772F8325622E2C229381310');
        $this->addSql('ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385B4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385E1DF977A');
        $this->addSql('DROP INDEX IDX_A5107385B772F8325622E2C229381310 ON psa_content_version_cta');
        $this->addSql('ALTER TABLE psa_content_version_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL, CHANGE page_version CONTENT_VERSION INT NOT NULL');
        $this->addSql('ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385B772F8325622E2C2FA8F2C85 FOREIGN KEY (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) REFERENCES psa_content_version (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_A5107385B772F8325622E2C2FA8F2C85 ON psa_content_version_cta (CONTENT_ID, LANGUE_ID, CONTENT_VERSION)');
        $this->addSql('ALTER TABLE psa_content_version_cta DROP PRIMARY KEY, ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, CONTENT_ID, LANGUE_ID, CONTENT_VERSION, PAGE_ZONE_CTA_TYPE)');

        $this->addSql('ALTER TABLE psa_page_zone_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL');

        $this->addSql('ALTER TABLE psa_page_multi_zone_cta DROP FOREIGN KEY FK_BDC5C30EB4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta DROP FOREIGN KEY FK_BDC5C30EE1DF977A');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta ADD CONSTRAINT FK_BDC5C30EB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta ADD CONSTRAINT FK_BDC5C30EE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE psa_page_zone_cta_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639B4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DF');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639E1DF977A');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DF FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_multi_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE psa_content_version_cta_cta DROP FOREIGN KEY FK_E9138D9BB4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_content_version_cta_cta DROP FOREIGN KEY FK_E9138D9BB772F8325622E2C229381310');
        $this->addSql('ALTER TABLE psa_content_version_cta_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_e9138d9bb772f8325622e2c229381310 ON psa_content_version_cta_cta');
        $this->addSql('CREATE INDEX IDX_E9138D9BB772F8325622E2C2FA8F2C85 ON psa_content_version_cta_cta (CONTENT_ID, LANGUE_ID, CONTENT_VERSION)');
        $this->addSql('ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BB772F8325622E2C229381310 FOREIGN KEY (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) REFERENCES psa_content_version (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602B4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602B4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602E1DF977A');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602B4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6 FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta DROP PRIMARY KEY, ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE, PAGE_ZONE_CTA_TYPE)');

        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta DROP FOREIGN KEY FK_F936EBBDB4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta DROP FOREIGN KEY FK_F936EBBDE1DF977A');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta CHANGE CTA_ID CTA_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta ADD CONSTRAINT FK_F936EBBDB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta ADD CONSTRAINT FK_F936EBBDE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta DROP PRIMARY KEY, ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_CTA_TYPE)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385B772F8325622E2C2FA8F2C85');
        $this->addSql('ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385E1DF977A');
        $this->addSql('ALTER TABLE psa_content_version_cta DROP FOREIGN KEY FK_A5107385B4EDB1E5622E2C2');
        $this->addSql('DROP INDEX IDX_A5107385B772F8325622E2C2FA8F2C85 ON psa_content_version_cta');
        $this->addSql('ALTER TABLE psa_content_version_cta DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE psa_content_version_cta CHANGE CTA_ID CTA_ID INT NOT NULL, CHANGE content_version PAGE_VERSION INT NOT NULL');
        $this->addSql('ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385B772F8325622E2C229381310 FOREIGN KEY (CONTENT_ID, LANGUE_ID, PAGE_VERSION) REFERENCES psa_content_version (CONTENT_ID, LANGUE_ID, CONTENT_VERSION)');
        $this->addSql('ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID)');
        $this->addSql('ALTER TABLE psa_content_version_cta ADD CONSTRAINT FK_A5107385B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID)');
        $this->addSql('CREATE INDEX IDX_A5107385B772F8325622E2C229381310 ON psa_content_version_cta (CONTENT_ID, LANGUE_ID, PAGE_VERSION)');
        $this->addSql('ALTER TABLE psa_content_version_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, CONTENT_ID, LANGUE_ID, PAGE_VERSION)');
        $this->addSql('ALTER TABLE psa_content_version_cta_cta DROP FOREIGN KEY FK_E9138D9BB772F8325622E2C2FA8F2C85');
        $this->addSql('ALTER TABLE psa_content_version_cta_cta DROP FOREIGN KEY FK_E9138D9BB4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_content_version_cta_cta CHANGE CTA_ID CTA_ID INT NOT NULL');
        $this->addSql('DROP INDEX idx_e9138d9bb772f8325622e2c2fa8f2c85 ON psa_content_version_cta_cta');
        $this->addSql('CREATE INDEX IDX_E9138D9BB772F8325622E2C229381310 ON psa_content_version_cta_cta (CONTENT_ID, LANGUE_ID, CONTENT_VERSION)');
        $this->addSql('ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BB772F8325622E2C2FA8F2C85 FOREIGN KEY (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) REFERENCES psa_content_version (CONTENT_ID, LANGUE_ID, CONTENT_VERSION) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_content_version_cta_cta ADD CONSTRAINT FK_E9138D9BB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta DROP FOREIGN KEY FK_BDC5C30EE1DF977A');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta DROP FOREIGN KEY FK_BDC5C30EB4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta ADD CONSTRAINT FK_BDC5C30EE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta ADD CONSTRAINT FK_BDC5C30EB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta DROP FOREIGN KEY FK_F936EBBDE1DF977A');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta DROP FOREIGN KEY FK_F936EBBDB4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta CHANGE CTA_ID CTA_ID INT NOT NULL');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta ADD CONSTRAINT FK_F936EBBDE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta ADD CONSTRAINT FK_F936EBBDB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_cta_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DF');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639E1DF977A');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta DROP FOREIGN KEY FK_605F4639B4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DF FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_multi_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta ADD CONSTRAINT FK_605F4639B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DFAC');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37E1DF977A');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP FOREIGN KEY FK_F83E37B4EDB1E5622E2C2');
        $this->addSql('DROP INDEX IDX_F83E37B4EDB1E5622E2C229381310BA07F8665F342437F55F4D23FD9DFA ON psa_page_multi_zone_multi_cta_cta');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta DROP PAGE_ZONE_MULTI_ID, DROP PAGE_ZONE_MULTI_TYPE');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37B4EDB1E5622E2C229381310BA07F8665F342437 FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER) REFERENCES psa_page_multi_zone (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID)');
        $this->addSql('ALTER TABLE psa_page_multi_zone_multi_cta_cta ADD CONSTRAINT FK_F83E37B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID)');
        $this->addSql('CREATE INDEX IDX_F83E37B4EDB1E5622E2C229381310BA07F8665F342437 ON psa_page_multi_zone_multi_cta_cta (PAGE_ID, LANGUE_ID, PAGE_VERSION, AREA_ID, ZONE_ORDER)');
        $this->addSql('ALTER TABLE psa_page_zone_cta CHANGE CTA_ID CTA_ID INT NOT NULL');
        $this->addSql('ALTER TABLE psa_page_zone_cta_cta CHANGE CTA_ID CTA_ID INT NOT NULL');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CB4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CE1DF977A');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta DROP FOREIGN KEY FK_59FECE2CB4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CB4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6 FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE)');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CE1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID)');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta ADD CONSTRAINT FK_59FECE2CB4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID)');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE)');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602B4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602E1DF977A');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta DROP FOREIGN KEY FK_6000D602B4EDB1E5622E2C2');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta CHANGE CTA_ID CTA_ID INT NOT NULL');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602B4EDB1E5622E2C229381310F15EAE15F55F4D23FD9DFAC6 FOREIGN KEY (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE) REFERENCES psa_page_zone_multi (PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE)');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602E1DF977A FOREIGN KEY (CTA_ID) REFERENCES psa_cta (ID)');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta ADD CONSTRAINT FK_6000D602B4EDB1E5622E2C2 FOREIGN KEY (PAGE_ID, LANGUE_ID) REFERENCES psa_page (PAGE_ID, LANGUE_ID)');
        $this->addSql('ALTER TABLE psa_page_zone_multi_cta_cta ADD PRIMARY KEY (PAGE_ZONE_CTA_CTA_ID, PAGE_ZONE_CTA_ID, PAGE_ID, LANGUE_ID, PAGE_VERSION, ZONE_TEMPLATE_ID, PAGE_ZONE_MULTI_ID, PAGE_ZONE_MULTI_TYPE)');
    }
}
