<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160323181843 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->addSql('ALTER TABLE psa_faq_rubrique_content DROP FOREIGN KEY psa_faq_rubrique_content_ibfk_3');
        $this->addSql('ALTER TABLE psa_vehicule_couleur DROP FOREIGN KEY psa_vehicule_couleur_ibfk_1');
        $this->addSql('ALTER TABLE psa_vehicule_criteres DROP FOREIGN KEY psa_vehicule_criteres_ibfk_1');
        $this->addSql('DROP TABLE psa_appmobile');
        $this->addSql('DROP TABLE temp_label');
        $this->addSql('DROP TABLE temp_traduction');
        $this->addSql('DROP TABLE psa_faq_rubrique');
        $this->addSql('DROP TABLE psa_faq_rubrique_content');
        $this->addSql('DROP TABLE psa_label_langue_temp');
        $this->addSql('DROP TABLE psa_perso_indicateur');
        $this->addSql('DROP TABLE psa_perso_product');
        $this->addSql('DROP TABLE psa_perso_product_media');
        $this->addSql('DROP TABLE psa_perso_product_page');
        $this->addSql('DROP TABLE psa_perso_product_term');
        $this->addSql('DROP TABLE psa_perso_profile');
        $this->addSql('DROP TABLE psa_vehicule');
        $this->addSql('DROP TABLE psa_vehicule_couleur');
        $this->addSql('DROP TABLE psa_vehicule_couleur_auto');
        $this->addSql('DROP TABLE psa_vehicule_criteres');
        $this->addSql("DELETE FROM psa_zone where ZONE_id = 779");

    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->addSql('CREATE TABLE temp_label (`LABEL` VARCHAR(500) NOT NULL COLLATE utf8_swedish_ci) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE temp_traduction (`KEY` VARCHAR(255) NOT NULL COLLATE utf8_general_ci, VALUE LONGTEXT NOT NULL COLLATE utf8_general_ci, PATH LONGTEXT NOT NULL COLLATE utf8_general_ci) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_appmobile (APPMOBILE_ID INT AUTO_INCREMENT NOT NULL, APPMOBILE_LABEL VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, APPMOBILE_LABEL_BO VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, APPMOBILE_TEXTE LONGTEXT NOT NULL COLLATE utf8_swedish_ci, APPMOBILE_URL_VISUEL VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, APPMOBILE_MODE_OUVERTURE VARCHAR(25) NOT NULL COLLATE utf8_swedish_ci, APPMOBILE_URL_GOOGLEPLAY VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, APPMOBILE_URL_APPLESTORE VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, APPMOBILE_URL_WINDOWS VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, SITE_ID INT DEFAULT NULL, LANGUE_ID INT DEFAULT NULL, MEDIA_ID INT DEFAULT NULL, INDEX IDX_B980AB20F1B5AEBC (SITE_ID), INDEX IDX_B980AB205622E2C2 (LANGUE_ID), INDEX IDX_B980AB2014E107D9 (MEDIA_ID), PRIMARY KEY(APPMOBILE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE psa_appmobile ADD CONSTRAINT FK_B980AB2014E107D9 FOREIGN KEY (MEDIA_ID) REFERENCES psa_media (MEDIA_ID)');
        $this->addSql('ALTER TABLE psa_appmobile ADD CONSTRAINT FK_B980AB205622E2C2 FOREIGN KEY (LANGUE_ID) REFERENCES psa_language (LANGUE_ID)');
        $this->addSql('ALTER TABLE psa_appmobile ADD CONSTRAINT FK_B980AB20F1B5AEBC FOREIGN KEY (SITE_ID) REFERENCES psa_site (SITE_ID)');
        $this->addSql('CREATE TABLE psa_faq_rubrique (FAQ_RUBRIQUE_ID INT AUTO_INCREMENT NOT NULL, LANGUE_ID INT NOT NULL, SITE_ID INT DEFAULT NULL, FAQ_RUBRIQUE_LABEL VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, FAQ_RUBRIQUE_PICTO INT DEFAULT NULL, INDEX psa_faq_rubrique_ibfk_1_idx (LANGUE_ID), INDEX psa_faq_rubrique_ibfk_2_idx (SITE_ID), INDEX psa_faq_rubrique_ibfk_3_idx (FAQ_RUBRIQUE_PICTO), PRIMARY KEY(FAQ_RUBRIQUE_ID, LANGUE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_faq_rubrique_content (FAQ_RUBRIQUE_ID INT NOT NULL, LANGUE_ID INT NOT NULL, CONTENT_ID INT NOT NULL, FAQ_RUBRIQUE_CONTENT_ORDER INT DEFAULT NULL, INDEX psa_faq_rubrique_ibfk_1_idx (FAQ_RUBRIQUE_ID), INDEX psa_faq_rubrique_ibfk_2_idx (LANGUE_ID), INDEX psa_faq_rubrique_ibfk_3_idx (CONTENT_ID), PRIMARY KEY(FAQ_RUBRIQUE_ID, LANGUE_ID, CONTENT_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE psa_faq_rubrique ADD CONSTRAINT psa_faq_rubrique_ibfk_1 FOREIGN KEY (LANGUE_ID) REFERENCES psa_language (LANGUE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_faq_rubrique ADD CONSTRAINT psa_faq_rubrique_ibfk_2 FOREIGN KEY (SITE_ID) REFERENCES psa_site (SITE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_faq_rubrique ADD CONSTRAINT psa_faq_rubrique_ibfk_3 FOREIGN KEY (FAQ_RUBRIQUE_PICTO) REFERENCES psa_media (MEDIA_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_faq_rubrique_content ADD CONSTRAINT psa_faq_rubrique_content_ibfk_1 FOREIGN KEY (LANGUE_ID) REFERENCES psa_language (LANGUE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_faq_rubrique_content ADD CONSTRAINT psa_faq_rubrique_content_ibfk_2 FOREIGN KEY (CONTENT_ID) REFERENCES psa_content (CONTENT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_faq_rubrique_content ADD CONSTRAINT psa_faq_rubrique_content_ibfk_3 FOREIGN KEY (FAQ_RUBRIQUE_ID) REFERENCES psa_faq_rubrique (FAQ_RUBRIQUE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE TABLE psa_label_langue_temp (LABEl_ID VARCHAR(255) NOT NULL COLLATE latin1_swedish_ci) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_perso_indicateur (INDICATEUR_ID INT AUTO_INCREMENT NOT NULL, INDICATEUR_LABEL VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, PRIMARY KEY(INDICATEUR_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_perso_product (PRODUCT_ID INT AUTO_INCREMENT NOT NULL, SITE_ID INT NOT NULL, PRODUCT_LABEL VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_ID INT DEFAULT NULL, INDEX FK_PRODUCT_SITE (SITE_ID), INDEX FK_PRODUCT_VEHICULE (VEHICULE_ID), PRIMARY KEY(PRODUCT_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_perso_product_media (PRODUCT_ID INT NOT NULL, MEDIA_ID INT NOT NULL, PRODUCT_MEDIA_TYPE VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, ORDER_MEDIA INT NOT NULL, INDEX FK_PRODUCT_MEDIA_MEDIA (MEDIA_ID), PRIMARY KEY(PRODUCT_ID, MEDIA_ID, PRODUCT_MEDIA_TYPE)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_perso_product_page (PRODUCT_PAGE_ID INT AUTO_INCREMENT NOT NULL, SITE_ID INT NOT NULL, PRODUCT_PAGE_URL VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, PRODUCT_PAGE_SCORE DOUBLE PRECISION NOT NULL, PRODUCT_ID INT NOT NULL, PRODUCT_PAGE_AJAX INT DEFAULT NULL, INDEX FK_PRODUCT_PAGE_SITE (SITE_ID), INDEX FK_PRODUCT_PAGE_PRODUCT (PRODUCT_ID), PRIMARY KEY(PRODUCT_PAGE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_perso_product_term (PRODUCT_TERM_ID INT AUTO_INCREMENT NOT NULL, SITE_ID INT NOT NULL, PRODUCT_TERM_LABEL VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, PRODUCT_ID INT DEFAULT NULL, PRODUCT_TERM_PRO TINYINT(1) DEFAULT NULL, INDEX FK_PRODUCT_TERM_SITE (SITE_ID), INDEX FK_PRODUCT_TERM_PRODUCT (PRODUCT_ID), PRIMARY KEY(PRODUCT_TERM_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_perso_profile (PROFILE_ID INT AUTO_INCREMENT NOT NULL, PROFILE_LABEL VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, PROFILE_I18N_KEY VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci COMMENT \'Clé de traduction du nom du profil\', UNIQUE INDEX PROFILE_I18N_KEY (PROFILE_I18N_KEY), PRIMARY KEY(PROFILE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_vehicule (VEHICULE_ID INT AUTO_INCREMENT NOT NULL, SITE_ID INT NOT NULL, LANGUE_ID INT NOT NULL, VEHICULE_LABEL VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_CATEG_LABEL VARCHAR(255) NOT NULL COLLATE utf8_swedish_ci, VEHICULE_LCDV6_CONFIG VARCHAR(6) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_GAMME_CONFIG VARCHAR(2) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_LCDV6_MANUAL VARCHAR(6) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_GAMME_MANUAL VARCHAR(2) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_GAMME_LABEL VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_MEDIA_ID_THUMBNAIL INT DEFAULT NULL, VEHICULE_MEDIA_ID_WEB1 INT DEFAULT NULL, VEHICULE_MEDIA_ID_WEB2 INT DEFAULT NULL, VEHICULE_MEDIA_ID_WEB3 INT DEFAULT NULL, VEHICULE_MEDIA_ID_MOB INT DEFAULT NULL, VEHICULE_DISPLAY_CASH_PRICE INT DEFAULT NULL, VEHICULE_DISPLAY_CREDIT_PRICE INT DEFAULT NULL, VEHICULE_CASH_PRICE VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_CASH_PRICE_TYPE VARCHAR(50) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_CASH_PRICE_LEGAL_MENTION TEXT DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_USE_FINANCIAL_SIMULATOR INT DEFAULT NULL, VEHICULE_CREDIT_PRICE_NEXT_RENT VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_CREDIT_PRICE_NEXT_RENT_LEGAL_MENTION TEXT DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_CREDIT_PRICE_FIRST_RENT VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_CREDIT_PRICE_FIRST_RENT_LEGAL_MENTION TEXT DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_FILTER_TYPE1 INT DEFAULT NULL, VEHICULE_FILTER_TYPE2 INT DEFAULT NULL, VEHICULE_FILTER_TYPE3 INT DEFAULT NULL, CODE_REGROUPEMENT_SILHOUETTE VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, INDEX SITE_ID (SITE_ID), INDEX LANGUE_ID (LANGUE_ID), INDEX VEHICULE_MEDIA_ID_THUMBNAIL (VEHICULE_MEDIA_ID_THUMBNAIL, VEHICULE_MEDIA_ID_WEB1, VEHICULE_MEDIA_ID_WEB2, VEHICULE_MEDIA_ID_WEB3), INDEX VEHICULE_MEDIA_ID_THUMBNAIL_2 (VEHICULE_MEDIA_ID_THUMBNAIL, VEHICULE_MEDIA_ID_WEB1, VEHICULE_MEDIA_ID_WEB2, VEHICULE_MEDIA_ID_WEB3), INDEX VEHICULE_MEDIA_ID_WEB1 (VEHICULE_MEDIA_ID_WEB1), INDEX VEHICULE_MEDIA_ID_WEB2 (VEHICULE_MEDIA_ID_WEB2), INDEX VEHICULE_MEDIA_ID_WEB3 (VEHICULE_MEDIA_ID_WEB3), INDEX VEHICULE_FILTER_TYPE1 (VEHICULE_FILTER_TYPE1), INDEX VEHICULE_FILTER_TYPE2 (VEHICULE_FILTER_TYPE2), INDEX VEHICULE_FILTER_TYPE3 (VEHICULE_FILTER_TYPE3), INDEX IDX_E79CB2F49CBB3E9F (VEHICULE_MEDIA_ID_THUMBNAIL), PRIMARY KEY(VEHICULE_ID, SITE_ID, LANGUE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_vehicule_couleur (VEHICULE_ID INT NOT NULL, SITE_ID INT NOT NULL, LANGUE_ID INT NOT NULL, VEHICULE_COULEUR_ORDER INT NOT NULL, VEHICULE_COULEUR_LABEL VARCHAR(100) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_COULEUR_MEDIA_ID_PICTO INT DEFAULT NULL, VEHICULE_COULEUR_CODE VARCHAR(50) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_COULEUR_LCDV6 VARCHAR(16) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_COULEUR_MEDIA_ID_BCKGRD_WEB1 INT DEFAULT NULL, VEHICULE_COULEUR_MEDIA_ID_BCKGRD_WEB2 INT DEFAULT NULL, VEHICULE_COULEUR_MEDIA_ID_BCKGRD_WEB3 INT DEFAULT NULL, VEHICULE_COULEUR_MEDIA_ID_CAR_WEB1 INT DEFAULT NULL, VEHICULE_COULEUR_MEDIA_ID_CAR_WEB2 INT DEFAULT NULL, VEHICULE_COULEUR_MEDIA_ID_CAR_WEB3 INT DEFAULT NULL, VEHICULE_COULEUR_MEDIA_ID_CAR_MOB1 INT DEFAULT NULL, INDEX psa_ws_vehicule_couleur_ibfk_1_idx (VEHICULE_ID), INDEX psa_ws_vehicule_couleur_ibfk_2_idx (SITE_ID), INDEX psa_ws_vehicule_couleur_ibfk_3_idx (LANGUE_ID), PRIMARY KEY(VEHICULE_ID, SITE_ID, LANGUE_ID, VEHICULE_COULEUR_ORDER)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_vehicule_couleur_auto (VEHICULE_ID INT NOT NULL, SITE_ID INT NOT NULL, LANGUE_ID INT NOT NULL, VEHICULE_COULEUR_ORDER INT NOT NULL, VEHICULE_LINK_BCKGRD_1 VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_LINK_BCKGRD_2 VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_LINK_BCKGRD_3 VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_LINK_TEINTE VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_LINK_ANGLE_1 VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_LINK_ANGLE_2 VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_LINK_ANGLE_3 VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, VEHICULE_LINK_ANGLE_MOBILE VARCHAR(255) DEFAULT NULL COLLATE utf8_swedish_ci, PRIMARY KEY(VEHICULE_ID, SITE_ID, LANGUE_ID, VEHICULE_COULEUR_ORDER)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE psa_vehicule_criteres (VEHICULE_ID INT NOT NULL, SITE_ID INT NOT NULL, LANGUE_ID INT NOT NULL, CRITERE_ID INT NOT NULL, INDEX psa_vehicule_criteres_ibfk_1_idx (VEHICULE_ID), INDEX psa_vehicule_criteres_ibfk_4_idx (CRITERE_ID), INDEX psa_vehicule_criteres_ibfk_3_idx (LANGUE_ID), INDEX psa_vehicule_criteres_ibfk_2_idx (SITE_ID), PRIMARY KEY(VEHICULE_ID, LANGUE_ID, SITE_ID, CRITERE_ID)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE psa_vehicule ADD CONSTRAINT psa_vehicule_ibfk_1 FOREIGN KEY (SITE_ID) REFERENCES psa_site (SITE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule ADD CONSTRAINT psa_vehicule_ibfk_2 FOREIGN KEY (LANGUE_ID) REFERENCES psa_language (LANGUE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule ADD CONSTRAINT psa_vehicule_ibfk_3 FOREIGN KEY (VEHICULE_MEDIA_ID_THUMBNAIL) REFERENCES psa_media (MEDIA_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule ADD CONSTRAINT psa_vehicule_ibfk_4 FOREIGN KEY (VEHICULE_MEDIA_ID_WEB1) REFERENCES psa_media (MEDIA_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule ADD CONSTRAINT psa_vehicule_ibfk_5 FOREIGN KEY (VEHICULE_MEDIA_ID_WEB2) REFERENCES psa_media (MEDIA_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule ADD CONSTRAINT psa_vehicule_ibfk_6 FOREIGN KEY (VEHICULE_MEDIA_ID_WEB3) REFERENCES psa_media (MEDIA_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule ADD CONSTRAINT psa_vehicule_ibfk_7 FOREIGN KEY (VEHICULE_FILTER_TYPE1) REFERENCES psa_critere (CRITERE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule ADD CONSTRAINT psa_vehicule_ibfk_8 FOREIGN KEY (VEHICULE_FILTER_TYPE2) REFERENCES psa_critere (CRITERE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule ADD CONSTRAINT psa_vehicule_ibfk_9 FOREIGN KEY (VEHICULE_FILTER_TYPE3) REFERENCES psa_critere (CRITERE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule_couleur ADD CONSTRAINT psa_vehicule_couleur_ibfk_1 FOREIGN KEY (VEHICULE_ID) REFERENCES psa_vehicule (VEHICULE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule_couleur ADD CONSTRAINT psa_vehicule_couleur_ibfk_2 FOREIGN KEY (SITE_ID) REFERENCES psa_site (SITE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule_couleur ADD CONSTRAINT psa_vehicule_couleur_ibfk_3 FOREIGN KEY (LANGUE_ID) REFERENCES psa_language (LANGUE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule_criteres ADD CONSTRAINT psa_vehicule_criteres_ibfk_1 FOREIGN KEY (VEHICULE_ID) REFERENCES psa_vehicule (VEHICULE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule_criteres ADD CONSTRAINT psa_vehicule_criteres_ibfk_2 FOREIGN KEY (SITE_ID) REFERENCES psa_site (SITE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule_criteres ADD CONSTRAINT psa_vehicule_criteres_ibfk_3 FOREIGN KEY (LANGUE_ID) REFERENCES psa_language (LANGUE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE psa_vehicule_criteres ADD CONSTRAINT psa_vehicule_criteres_ibfk_4 FOREIGN KEY (CRITERE_ID) REFERENCES psa_critere (CRITERE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql("INSERT INTO `psa_zone` (`ZONE_ID`, `ZONE_TYPE_ID`, `ZONE_LABEL`, `ZONE_FREE`, `ZONE_COMMENT`, `ZONE_BO_PATH`, `ZONE_FO_PATH`, `ZONE_IFRAME`, `ZONE_AJAX`, `ZONE_PROGRAM`, `ZONE_DB_MULTI`, `ZONE_IMAGE`, `ZONE_CATEGORY_ID`, `ZONE_CONTENT`, `PLUGIN_ID`) VALUES
         (779, 1, 'NDP_PC62_Application_Boussole', 0, NULL, 'Cms_Page_Ndp_Pc62ApplicationBoussole', 'Pc62ApplicationBoussoleStrategy', 0, 0, 0, NULL, NULL, 28, 0, '')
         ");
    }
}
