<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20151117164314 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->addSql("DELETE FROM `psa_zone_template` WHERE TEMPLATE_PAGE_ID IN (1504,1505,1510,1511)");
        $this->addSql("DELETE FROM `psa_template_page` WHERE TEMPLATE_PAGE_ID IN (1504,1505,1510,1511)");
        $this->addSql("DELETE FROM `psa_template_page_area` WHERE TEMPLATE_PAGE_ID IN (1504,1505,1510,1511)");

        $this->addSql("REPLACE INTO `psa_template_page` (`TEMPLATE_PAGE_ID`,`SITE_ID`,`PAGE_TYPE_ID`,`TEMPLATE_PAGE_LABEL`,`TEMPLATE_PAGE_GENERAL`) VALUES
                        (1513,2,15,'AGILE - DEMO - Sprint2 - NavFull',NULL),
                        (1015,2,33,'AGILE - DEMO - Sprint2 - NavLight',NULL),
                        (1518,2,31,'AGILE - DEMO - Sprint2 - Dealer Locator',NULL)");

        $this->addSql("INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6010,'PT21',1513,10,798,1,1,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6010,`ZONE_TEMPLATE_LABEL`='PT21',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=10,`ZONE_ID`=798,`ZONE_TEMPLATE_ORDER`=1,`ZONE_TEMPLATE_MOBILE_ORDER`=1,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6011,'PN7',1513,121,791,2,2,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6011,`ZONE_TEMPLATE_LABEL`='PN7',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=121,`ZONE_ID`=791,`ZONE_TEMPLATE_ORDER`=2,`ZONE_TEMPLATE_MOBILE_ORDER`=2,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6012,'PC5',1513,150,776,4,4,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6012,`ZONE_TEMPLATE_LABEL`='PC5',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`ZONE_ID`=776,`ZONE_TEMPLATE_ORDER`=4,`ZONE_TEMPLATE_MOBILE_ORDER`=4,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6013,'PC7',1513,150,781,5,5,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6013,`ZONE_TEMPLATE_LABEL`='PC7',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`ZONE_ID`=781,`ZONE_TEMPLATE_ORDER`=5,`ZONE_TEMPLATE_MOBILE_ORDER`=5,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                         (6014,'PC12',1513,150,760,7,7,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6014,`ZONE_TEMPLATE_LABEL`='PC12',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`ZONE_ID`=760,`ZONE_TEMPLATE_ORDER`=7,`ZONE_TEMPLATE_MOBILE_ORDER`=7,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6028,'PF11',1513,150,812,11,11,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6028,`ZONE_TEMPLATE_LABEL`='PF11',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`ZONE_ID`=812,`ZONE_TEMPLATE_ORDER`=11,`ZONE_TEMPLATE_MOBILE_ORDER`=11,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6029,'PC68',1513,150,766,9,9,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6029,`ZONE_TEMPLATE_LABEL`='PC68',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`ZONE_ID`=766,`ZONE_TEMPLATE_ORDER`=9,`ZONE_TEMPLATE_MOBILE_ORDER`=9,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6030,'PC2',1513,150,750,3,3,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6030,`ZONE_TEMPLATE_LABEL`='PC2',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`ZONE_ID`=750,`ZONE_TEMPLATE_ORDER`=3,`ZONE_TEMPLATE_MOBILE_ORDER`=3,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6031,'PC69',1513,150,767,10,10,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6031,`ZONE_TEMPLATE_LABEL`='PC69',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`ZONE_ID`=767,`ZONE_TEMPLATE_ORDER`=10,`ZONE_TEMPLATE_MOBILE_ORDER`=10,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6032,'PC40',1513,150,771,8,8,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6032,`ZONE_TEMPLATE_LABEL`='PC40',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`ZONE_ID`=771,`ZONE_TEMPLATE_ORDER`=8,`ZONE_TEMPLATE_MOBILE_ORDER`=8,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6033,'PC9',1513,150,752,6,6,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6033,`ZONE_TEMPLATE_LABEL`='PC9',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`ZONE_ID`=752,`ZONE_TEMPLATE_ORDER`=6,`ZONE_TEMPLATE_MOBILE_ORDER`=6,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6046,'PT2',1513,122,800,12,12,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6046,`ZONE_TEMPLATE_LABEL`='PT2',`TEMPLATE_PAGE_ID`=1513,`AREA_ID`=122,`ZONE_ID`=800,`ZONE_TEMPLATE_ORDER`=12,`ZONE_TEMPLATE_MOBILE_ORDER`=12,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6015,'PT21',1515,10,798,1,1,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6015,`ZONE_TEMPLATE_LABEL`='PT21',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=10,`ZONE_ID`=798,`ZONE_TEMPLATE_ORDER`=1,`ZONE_TEMPLATE_MOBILE_ORDER`=1,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6016,'PN7',1515,151,791,2,2,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6016,`ZONE_TEMPLATE_LABEL`='PN7',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=151,`ZONE_ID`=791,`ZONE_TEMPLATE_ORDER`=2,`ZONE_TEMPLATE_MOBILE_ORDER`=2,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6017,'PC5',1515,150,776,6,6,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6017,`ZONE_TEMPLATE_LABEL`='PC5',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`ZONE_ID`=776,`ZONE_TEMPLATE_ORDER`=6,`ZONE_TEMPLATE_MOBILE_ORDER`=6,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6018,'PC7',1515,150,781,7,7,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6018,`ZONE_TEMPLATE_LABEL`='PC7',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`ZONE_ID`=781,`ZONE_TEMPLATE_ORDER`=7,`ZONE_TEMPLATE_MOBILE_ORDER`=7	,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6019,'PC12',1515,150,760,9,9,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6019,`ZONE_TEMPLATE_LABEL`='PC12',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`ZONE_ID`=760,`ZONE_TEMPLATE_ORDER`=9,`ZONE_TEMPLATE_MOBILE_ORDER`=9,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6020,'PF2',1515,151,830,3,3,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6020,`ZONE_TEMPLATE_LABEL`='PF2',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=151,`ZONE_ID`=830,`ZONE_TEMPLATE_ORDER`=3,`ZONE_TEMPLATE_MOBILE_ORDER`=4,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6034,'PN14',1515,151,822,4,4,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6034,`ZONE_TEMPLATE_LABEL`='PN14',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=151,`ZONE_ID`=822,`ZONE_TEMPLATE_ORDER`=4,`ZONE_TEMPLATE_MOBILE_ORDER`=3,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6035,'PC2',1515,150,750,5,5,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6035,`ZONE_TEMPLATE_LABEL`='PC2',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`ZONE_ID`=750,`ZONE_TEMPLATE_ORDER`=5,`ZONE_TEMPLATE_MOBILE_ORDER`=5,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6036,'PC40',1515,150,771,10,10,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6036,`ZONE_TEMPLATE_LABEL`='PC40',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`ZONE_ID`=771,`ZONE_TEMPLATE_ORDER`=10,`ZONE_TEMPLATE_MOBILE_ORDER`=10,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6037,'PC68',1515,150,766,11,11,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6037,`ZONE_TEMPLATE_LABEL`='PC68',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`ZONE_ID`=766,`ZONE_TEMPLATE_ORDER`=11,`ZONE_TEMPLATE_MOBILE_ORDER`=11,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6038,'PC69',1515,150,767,12,12,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6038,`ZONE_TEMPLATE_LABEL`='PC69',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`ZONE_ID`=767,`ZONE_TEMPLATE_ORDER`=12,`ZONE_TEMPLATE_MOBILE_ORDER`=12,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6039,'PC9',1515,150,752,8,8,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6039,`ZONE_TEMPLATE_LABEL`='PC9',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`ZONE_ID`=752,`ZONE_TEMPLATE_ORDER`=8,`ZONE_TEMPLATE_MOBILE_ORDER`=8,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6040,'PF11',1515,150,812,13,13,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6040,`ZONE_TEMPLATE_LABEL`='PF11',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`ZONE_ID`=812,`ZONE_TEMPLATE_ORDER`=13,`ZONE_TEMPLATE_MOBILE_ORDER`=13,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6045,'PT2',1515,122,800,14,NULL,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6045,`ZONE_TEMPLATE_LABEL`='PT2',`TEMPLATE_PAGE_ID`=1515,`AREA_ID`=122,`ZONE_ID`=800,`ZONE_TEMPLATE_ORDER`=14,`ZONE_TEMPLATE_MOBILE_ORDER`=14,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6041,'PT21',1518,10,798,1,1,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6041,`ZONE_TEMPLATE_LABEL`='PT21',`TEMPLATE_PAGE_ID`=1518,`AREA_ID`=10,`ZONE_ID`=798,`ZONE_TEMPLATE_ORDER`=1,`ZONE_TEMPLATE_MOBILE_ORDER`=1,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6042,'PN7',1518,121,791,2,2,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6042,`ZONE_TEMPLATE_LABEL`='PN7',`TEMPLATE_PAGE_ID`=1518,`AREA_ID`=121,`ZONE_ID`=791,`ZONE_TEMPLATE_ORDER`=2,`ZONE_TEMPLATE_MOBILE_ORDER`=2,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6043,'PF11',1518,148,812,3,3,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6043,`ZONE_TEMPLATE_LABEL`='PF11',`TEMPLATE_PAGE_ID`=1518,`AREA_ID`=148,`ZONE_ID`=812,`ZONE_TEMPLATE_ORDER`=3,`ZONE_TEMPLATE_MOBILE_ORDER`=3,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;
                        INSERT INTO `psa_zone_template` (`ZONE_TEMPLATE_ID`,`ZONE_TEMPLATE_LABEL`,`TEMPLATE_PAGE_ID`,`AREA_ID`,`ZONE_ID`,`ZONE_TEMPLATE_ORDER`,`ZONE_TEMPLATE_MOBILE_ORDER`,`ZONE_TEMPLATE_TABLET_ORDER`,`ZONE_TEMPLATE_TV_ORDER`,`ZONE_CACHE_TIME`) VALUES
                        (6044,'PT2',1518,122,800,4,4,NULL,NULL,-2) ON DUPLICATE KEY UPDATE
                        `ZONE_TEMPLATE_ID`=6044,`ZONE_TEMPLATE_LABEL`='PT2',`TEMPLATE_PAGE_ID`=1518,`AREA_ID`=122,`ZONE_ID`=800,`ZONE_TEMPLATE_ORDER`=4,`ZONE_TEMPLATE_MOBILE_ORDER`=4,`ZONE_TEMPLATE_TABLET_ORDER`=NULL,`ZONE_TEMPLATE_TV_ORDER`=NULL,`ZONE_CACHE_TIME`=-2;");

        $this->addSql("INSERT INTO `psa_template_page_area` (`TEMPLATE_PAGE_ID`,`AREA_ID`,`TEMPLATE_PAGE_AREA_ORDER`,`LIGNE`,`COLONNE`,`LARGEUR`,`HAUTEUR`,`IS_DROPPABLE`) VALUES
                        (1513,10,1,1,1,4,1,0) ON DUPLICATE KEY UPDATE
                        `TEMPLATE_PAGE_ID`=1513,`AREA_ID`=10,`TEMPLATE_PAGE_AREA_ORDER`=1,`LIGNE`=1,`COLONNE`=1,`LARGEUR`=4,`HAUTEUR`=1,`IS_DROPPABLE`=0;
                        INSERT INTO `psa_template_page_area` (`TEMPLATE_PAGE_ID`,`AREA_ID`,`TEMPLATE_PAGE_AREA_ORDER`,`LIGNE`,`COLONNE`,`LARGEUR`,`HAUTEUR`,`IS_DROPPABLE`) VALUES
                        (1513,121,2,2,1,4,1,0) ON DUPLICATE KEY UPDATE
                        `TEMPLATE_PAGE_ID`=1513,`AREA_ID`=121,`TEMPLATE_PAGE_AREA_ORDER`=2,`LIGNE`=2,`COLONNE`=1,`LARGEUR`=4,`HAUTEUR`=1,`IS_DROPPABLE`=0;
                        INSERT INTO `psa_template_page_area` (`TEMPLATE_PAGE_ID`,`AREA_ID`,`TEMPLATE_PAGE_AREA_ORDER`,`LIGNE`,`COLONNE`,`LARGEUR`,`HAUTEUR`,`IS_DROPPABLE`) VALUES
                        (1513,122,4,4,1,4,1,0) ON DUPLICATE KEY UPDATE
                        `TEMPLATE_PAGE_ID`=1513,`AREA_ID`=122,`TEMPLATE_PAGE_AREA_ORDER`=4,`LIGNE`=4,`COLONNE`=1,`LARGEUR`=4,`HAUTEUR`=1,`IS_DROPPABLE`=0;
                        INSERT INTO `psa_template_page_area` (`TEMPLATE_PAGE_ID`,`AREA_ID`,`TEMPLATE_PAGE_AREA_ORDER`,`LIGNE`,`COLONNE`,`LARGEUR`,`HAUTEUR`,`IS_DROPPABLE`) VALUES
                        (1513,150,3,3,1,4,1,0) ON DUPLICATE KEY UPDATE
                        `TEMPLATE_PAGE_ID`=1513,`AREA_ID`=150,`TEMPLATE_PAGE_AREA_ORDER`=3,`LIGNE`=3,`COLONNE`=1,`LARGEUR`=4,`HAUTEUR`=1,`IS_DROPPABLE`=0;
                        INSERT INTO `psa_template_page_area` (`TEMPLATE_PAGE_ID`,`AREA_ID`,`TEMPLATE_PAGE_AREA_ORDER`,`LIGNE`,`COLONNE`,`LARGEUR`,`HAUTEUR`,`IS_DROPPABLE`) VALUES
                        (1515,10,1,1,1,4,1,0) ON DUPLICATE KEY UPDATE
                        `TEMPLATE_PAGE_ID`=1515,`AREA_ID`=10,`TEMPLATE_PAGE_AREA_ORDER`=1,`LIGNE`=1,`COLONNE`=1,`LARGEUR`=4,`HAUTEUR`=1,`IS_DROPPABLE`=0;
                        INSERT INTO `psa_template_page_area` (`TEMPLATE_PAGE_ID`,`AREA_ID`,`TEMPLATE_PAGE_AREA_ORDER`,`LIGNE`,`COLONNE`,`LARGEUR`,`HAUTEUR`,`IS_DROPPABLE`) VALUES
                        (1515,122,4,4,1,4,1,0) ON DUPLICATE KEY UPDATE
                        `TEMPLATE_PAGE_ID`=1515,`AREA_ID`=122,`TEMPLATE_PAGE_AREA_ORDER`=4,`LIGNE`=4,`COLONNE`=1,`LARGEUR`=4,`HAUTEUR`=1,`IS_DROPPABLE`=0;
                        INSERT INTO `psa_template_page_area` (`TEMPLATE_PAGE_ID`,`AREA_ID`,`TEMPLATE_PAGE_AREA_ORDER`,`LIGNE`,`COLONNE`,`LARGEUR`,`HAUTEUR`,`IS_DROPPABLE`) VALUES
                        (1515,150,3,3,1,4,1,0) ON DUPLICATE KEY UPDATE
                        `TEMPLATE_PAGE_ID`=1515,`AREA_ID`=150,`TEMPLATE_PAGE_AREA_ORDER`=3,`LIGNE`=3,`COLONNE`=1,`LARGEUR`=4,`HAUTEUR`=1,`IS_DROPPABLE`=0;
                        INSERT INTO `psa_template_page_area` (`TEMPLATE_PAGE_ID`,`AREA_ID`,`TEMPLATE_PAGE_AREA_ORDER`,`LIGNE`,`COLONNE`,`LARGEUR`,`HAUTEUR`,`IS_DROPPABLE`) VALUES
                        (1515,151,2,2,1,4,1,0) ON DUPLICATE KEY UPDATE
                        `TEMPLATE_PAGE_ID`=1515,`AREA_ID`=151,`TEMPLATE_PAGE_AREA_ORDER`=2,`LIGNE`=2,`COLONNE`=1,`LARGEUR`=4,`HAUTEUR`=1,`IS_DROPPABLE`=0;");

        $this->addSql("INSERT INTO `psa_template_page_area` (`TEMPLATE_PAGE_ID`,`AREA_ID`,`TEMPLATE_PAGE_AREA_ORDER`,`LIGNE`,`COLONNE`,`LARGEUR`,`HAUTEUR`,`IS_DROPPABLE`) VALUES
                        (1518,10,1,1,1,4,1,0),
                        (1518,121,2,2,1,4,1,0),
                        (1518,122,4,4,1,4,1,0),
                        (1518,148,3,3,1,4,1,0)");

    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
