imports:
    - { resource: config.yml }
    - { resource: parameters_app_rec.yml }
    - { resource: parameters_db_rec.yml }
    - { resource: parameters_proxy_rec.yml }

# Doctrine Migration (to be removed once BO is installed)
doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        console:
            type:  console
assetic:
    use_controller: true
    
sonata_cache:
    caches:
        symfony:
            token: 30SG2y20C48DbF30Q0Nc5lYDgYve6W23 # token used to clear the related cache
            php_cache_enabled: true # Optional (default: false), clear APC or PHP OPcache
            types:  ['translations', 'routing', 'container', 'all']
            servers:
                - { domain: recette-master.staging.psa-ndp.interakting.org, ip: 127.0.0.1, port: 80}
