
imports:
    - { resource: parameters.yml }
    - { resource: parameters_app.yml }
    - { resource: parameters_app_cache.yml }
    - { resource: parameters_env.php }
    - { resource: security.yml }
    - { resource: datalayer.yml }
    - { resource: assets_version.yml }

framework:
    esi:             { enabled: true }
    translator:      { fallback: "%default_locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'smarty']
    default_locale:  "%default_locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       { path: /_fragment }
    http_method_override: true
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        media_server: @psa_ndp.services.media_server_initializer


services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - OpenOrchestraFrontBundle
        - OpenOrchestraDisplayBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
                     enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
          string_functions:
            field: DoctrineExtensions\Query\Mysql\Field    


# Swiftmailer Configuration
#swiftmailer:
   # transport: "%mailer_transport%"
   # host:      "%mailer_host%"
    #username:  "%mailer_user%"
    #password:  "%mailer_password%"
   # spool:     { type: memory }

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://localhost
            logging: %kernel.debug%

# Orchestra
open_orchestra_base:
    object_manager: doctrine.orm.entity_manager
    encryption_key: %encryption_key%

# Smarty
smarty:
    globals:
        media_server: "@psa_ndp.services.media_server_initializer"


fos_http_cache:
    proxy_client:
        varnish:
            servers: localhost
            base_url: localhost
        default: varnish


#twig for mobile (use for node show.html.twig template)
open_orchestra_front:
    routing_type: file
    devices:
        web: ~
        mobile:
            parent: web

itkg_consumer: ~

