parameters:
    proxy:
        isActive: true
        protocole : http
        host : relaishttp.sgppsa.com
        port : 80
        login : mdendp00
        password : rcpel8z6
        CURLOPT_PROXY: 'http://relaishttp.sgppsa.com'
        CURLOPT_PROXYPORT: 80
        CURLOPT_PROXYUSERPWD: 'mdendp00:rcpel8z6'
