---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: 'psa-ndp'
        memory: '1024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.10.10
            forwarded_port: {  }
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            qqUlfbntW2Zq:
                owner: vagrant
                group: www-data
                source: '/var/www/psa-ndp'
                target: /var/www
                sync_type: default # nfs leads to incoherent states
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - curl
        - htop
        - subversion
        - graphicsmagick
        - git
        - phpmyadmin
        - sendmail-bin
        - sendmail
        - php-apc
        - acl
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - deflate
        - ldap
        - rewrite
        - ssl
        - headers
    vhosts:
        reference:
            servername: reference.psa-ndp.com
            serveraliases:
                - www.reference.psa-ndp.com
            docroot: /var/www/backend/public/master
            port: '80'
            setenv:
                - 'TYPE_ENVIRONNEMENT VM'
                - 'SYMFONY__HTTP__MEDIA http://media.psa-ndp.com'
                - 'SYMFONY__REDIS__CONNECTION tcp://127.0.0.1:6379'
                - 'HTTP_BACKEND backend.psa-ndp.com'
                - 'FRONTEND_VAR_PATH /var/frontend'
            directories:
                reference:
                    provider: directory
                    path: /var/www/backend/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        front:
            servername: master.psa-ndp.com
            serveraliases:
                - fr.psa-ndp.com
                - be.psa-ndp.com
                - de.psa-ndp.com
                - cz.psa-ndp.com
                - master.psa-ndp.com
            docroot: /var/www/frontend/web
            port: '80'
            setenv:
                - 'TYPE_ENVIRONNEMENT VM'
                - 'SYMFONY__HTTP__MEDIA http://media.psa-ndp.com'
                - 'SYMFONY__REDIS__CONNECTION tcp://127.0.0.1:6379'
                - 'HTTP_BACKEND backend.psa-ndp.com'
                - 'FRONTEND_VAR_PATH /var/frontend'
            directories:
                front:
                    provider: directory
                    path: /var/www/frontend/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: "<IfModule mod_proxy.c>\n   SSLProxyEngine On\n   ProxyRequests On\n    ProxyPass   /images           http://re7.dpdcr.peugeot.com/images connectiontimeout=5 timeout=30\n            ProxyPass   /forms/v2         http://re7.dpdcr.peugeot.com/forms/v2\n            ProxyPass   /version/         http://re7.dpdcr.peugeot.com/version/\n            ProxyPass   /services/        http://re7.dpdcr.peugeot.com/services/\n            ProxyPass   /dcr/             http://re7.dpdcr.peugeot.com/dcr/\n            ProxyPass   /connexion        http://re7.dpdcr.peugeot.com/connexion\n            ProxyPass   /index/postajax   http://re7.dpdcr.peugeot.com/index/postajax\n   ProxyVia On\n </IfModule>\n"
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        media:
            servername: media.psa-ndp.com
            docroot: /var/www/backend/public/media
            port: '80'
            setenv:
                - 'TYPE_ENVIRONNEMENT VM'
                - 'HTTP_MEDIA media.psa-ndp.com'
                - 'HTTP_BACKEND backend.psa-ndp.com'
                - 'FRONTEND_VAR_PATH /var/frontend'
                - 'SYMFONY__HTTP__MEDIA http://media.psa-ndp.com'
                - 'SYMFONY__REDIS__CONNECTION tcp://127.0.0.1:6379'
            directories:
                media:
                    provider: directory
                    path: /var/www/backend/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: "   Alias /library /var/www/backend/library\n   Alias /modules /var/www/backend/public/media/modules\n  ProxyPassMatch ^/library/(.*\\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/backend/library/$1\n  ProxyPassMatch ^/modules/(.*\\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/backend/public/media/modules/$1\n  AddType video/mp4 .mp4\n  AddType video/webm .webm \n  Header set Access-Control-Allow-Origin \"*\""
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        backend:
            servername: backend.psa-ndp.com
            docroot: /var/www/backend/public/backend
            port: '80'
            setenv:
                - 'TYPE_ENVIRONNEMENT VM'
                - 'HTTP_MEDIA media.psa-ndp.com'
                - 'HTTP_BACKEND backend.psa-ndp.com'
                - 'FRONTEND_VAR_PATH /var/frontend'
                - 'BACKEND_VAR_PATH /var/backend'
                - 'FRONTEND_APP_PATH /var/www/frontend'
                - 'SYMFONY__HTTP__MEDIA http://media.psa-ndp.com'
                - 'SYMFONY__REDIS__CONNECTION tcp://127.0.0.1:6379'
            directories:
                backend:
                    provider: directory
                    path: /var/www/backend/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: "Alias /library/ /var/www/backend/library/\n  Alias /videos/ /var/www/backend/public/media/video/\n  Alias /modules/ /var/www/backend/public/media/modules/\n  Alias /plugins/ /var/www/backend/public/media/plugins/\n  ProxyPassMatch ^/library/(.*\\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/backend/library/$1\n  ProxyPassMatch ^/modules/(.*\\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/backend/public/media/modules/$1\n   AddType video/mp4 .mp4\n  AddType video/webm .webm"
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        mdznb3lltjqb:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - gd
            - imagick
            - intl
            - ldap
            - mbstring
            - mcrypt
            - mysql
            - mysqlnd
        pear: {  }
        pecl:
            - mongo
            - mysqlnd_ms
            - redis
            - yaml
            - pecl_http
            - imagick
            - igbinary
            - phar
    ini:
        display_errors: On
        session.save_path: /var/lib/php/session
        always_populate_raw_post_data: '0'
        error_reporting: 'E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_STRICT'
        expose_php: '0'
        log_errors: '1'
        short_open_tag: '1'
        memory_limit: 768M
        max_execution_time: '60'
        sendmail_path: '/usr/bin/env catchmail -f mail@psa-ndp.com'
        include_path: '.:/var/www/backend/application/configs:/var/www/backend/library'
        extension: igbinary.so
        session.serialize_handler: igbinary
        igbinary.compact_strings: On
    timezone: Europe/Paris
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_connect_back: '0'
        xdebug.remote_enable: '0'
        xdebug.remote_handler: dbgp
        xdebug.remote_host: 192.168.56.101
        xdebug.remote_mode: req
        xdebug.idekey: phpstorm-idekey
        xdebug.remote_autostart: '0'
        xdebug.profiler_enable_trigger: 1
xhprof:
    install: '1'
wpcli:
    install: '0'
    version: ''
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '1'
    npm_packages:
        - yo
        - gulp
        - bower
        - coffee-script
        - jshint
        - csslint
        - eslint
        - nodemon
        - grunt-cli
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '1'
    override_options: {  }
    root_password: root
    adminer: '1'
    databases:
        psa-ndp:
            grant:
                - ALL
            name: psa-ndp
            host: localhost
            user: psa-ndp
            password: psa-ndp
            sql_file: /var/www/_init/fixtures/psa-ndp.sql
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases:
        ndp:
            name: ndp
            user: ndp
            password: ndp
redis:
    install: '1'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: ''
        port: ''

